{
  "hash": "593d26b4c3a0928602c2e00464d7dd7e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Philadelphia Housing Model\"\nsubtitle: \"Home Price Prediction in Philadelphia\"\n\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n::::: grid\n::: g-col-6\n**AUTHOR**\n\nZhuosi Yang, Veronica Zheng, Yiting Zhong, Coco Zhou\n:::\n\n::: g-col-6\n**PUBLISHED**\n\nMarch 14, 2026\n:::\n:::::\n\n**Content:**\n\n-   Data Sources\n-   Data Preparation & Cleaning\n-   Exploratory Data Analysis\n-   Feature Engineering\n-   Model Building\n-   Diagnostic plots\n-   Conclusion & Interpretations\n\n## Data Sources\n\n### Primary Dataset: Philadelphia Property Sales\n\n**Source:** [Philadelphia Property Sales](https://catalog.data.gov/dataset/philadelphia-properties-and-assessment-history)\n\nThis study uses the Philadelphia Property Sales dataset as the primary data source for modeling residential housing prices. The dataset contains detailed information on property transactions and structural housing characteristics.\n\nThe primary dataset contains property-level structural characteristics and sale information used to model housing sale prices. The following variables were included:\n\n-   **Sale price** *(target variable)*\n-   **Year built**\n-   **Housing size (Total Livable Area)**\n-   **Number of bedrooms**\n-   **Number of bathrooms**\n-   **Interior condition**\n-   **Exterior condition**\n-   **Garage spaces**\n-   **Fireplaces**\n-   **Basements**\n\nThe corresponding variable names in the dataset are:\n\n-   `sale_price`\n-   `year_built`\n-   `total_livable_area`\n-   `number_of_bedrooms`\n-   `number_of_bathrooms`\n-   `interior_condition`\n-   `exterior_condition`\n-   `garage_spaces`\n-   `fireplaces`\n-   `basements`\n\nThe variable **`sale_date`** is used only for filtering observations to include property transactions from **2023–2024**.\n\n### Secondary Spatial and Neighborhood Datasets\n\nSeveral spatial variables were incorporated to capture neighborhood characteristics and accessibility factors that influence housing prices.\n\n**Source:** [OpenDataPhilly](https://opendataphilly.org/)\n\n#### Crime\n\nCrime data were included to represent neighborhood safety conditions.\n\n**Source:**\\\n[Philadelphia Crime Incidents](https://opendataphilly.org/datasets/crime-incidents/)\n\n#### Schools\n\nSchool locations were included to represent access to educational resources.\n\n**Source:**\\\n[Philadelphia Schools](https://opendataphilly.org/datasets/schools/)\n\n#### Major Parks\n\nParks were included to represent access to green space and recreational amenities.\n\n**Source:**\\\n[Philadelphia PPR Properties](https://opendataphilly.org/datasets/ppr-properties/)\n\n\n#### Transit Stops\n\nTransit stop locations were used to represent access to public transportation.\n\n**Source:**\\\n[SEPTA All Transit Stops (Bus, Trolley, Rail)](https://opendataphilly.org/datasets/septa-routes-stops-locations/)\n\n#### Vacant Properties\n\nVacant property locations were included to represent neighborhood vacancy conditions.\n\n**Source:**\\\n[Philadelphia Vacant Property Indicators](https://opendataphilly.org/datasets/vacant-property-indicators/)\n\n#### Census Demographic Data\n\nDemographic characteristics were derived from U.S. Census data.\n\nVariables include:\n\n-   Median household income\\\n-   Percentage of households without a vehicle\n\n#### Interaction and Nonlinear Variables\n\nAdditional interaction variables were created to capture relationships between transportation access and neighborhood characteristics.\n\n-   Transit accessibility × percentage of households with no vehicle\n\n### Reasons for choosing the datasets:\n\nOur model constructs a property-level dataset designed to investigate the physical characteristics of each home and the spatial context around it because housing prices are influenced not only by structural attributes, but also by neighborhood conditions. For this reason, the dataset combines traditional housing attributes with a series of engineered spatial variables.\n\nThe structural characteristics describe the physical condition of each home. These include the year the structure was built, the total livable area of the home, the number of bedrooms, the number of bathrooms, and the presence of features such as garages, fireplaces, and basements. Interior and exterior condition ratings were also included to capture the quality of the structure. Based on buyers’ needs, different structural features provide different types of convenience for different groups of people, which allows properties to be marketed more effectively and potentially achieve more favorable sale prices. Homes with larger living areas and better overall quality also tend to command higher prices. These factors are inherently reflected in the structural features of the property.\n\nBeyond the structure of the house, the surrounding neighborhood environment is important in determining property value. One key factor is crime exposure. The assumption is that homes located in areas with higher nearby crime activity may experience lower property values. Access to public amenities and services was also important for property values. Shorter distances to public transit indicate easier access to employment centers and mobility options, which can increase the desirability of a property. Similarly, access to green space provides recreational and environmental benefits, and homes located closer to parks are often perceived as more attractive to buyers. Access to social infrastructure, such as schools, was also incorporated. These services contribute to neighborhood livability and can influence property value.\n\nThe socioeconomic context from U.S. Census data was also incorporated. Median household income and the percentage of households without a vehicle were attached to each property through spatial joins with census geography. Median income serves as a proxy for neighborhood economic conditions. An interaction variable between transit accessibility and the percentage of households without vehicles was created to capture local transportation dependence, reflecting that transit access may be more valuable in areas where residents rely more heavily on public transportation.\n\nFinally, neighborhood physical conditions were measured through the presence of vacant properties. Higher concentrations of vacancy may signal neighborhood disinvestment, which can negatively influence nearby property values.\n\nOverall, the resulting model incorporates a comprehensive set of property and environmental factors that influence housing sale prices, better reflecting real-world housing market conditions.\n\n## Data Preparation & Cleaning\n\n\n\nLoad primary data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load dataset\nopa <- read_sf(here(\"data\", \"opa_properties_public.geojson\"))\n```\n:::\n\n\nClean primary data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#filter residential data category code=1\nopa_res <- opa %>%\n  filter(category_code == 1)\n\n#filter sale_date range 2023-2024\nopa_res_date <- opa_res %>%\n  filter(\n    sale_date >= \"2023-01-01 00:00:00\",\n    sale_date <= \"2024-12-31 23:59:59\"\n  )\n\n\nopa_res_date <- opa_res_date %>%\n  mutate(\n    basement_score = dplyr::recode(\n      basements,\n      \"A\" = 9,\n      \"B\" = 8,\n      \"C\" = 7,\n      \"D\" = 6,\n      \"E\" = 5,\n      \"F\" = 4,\n      \"G\" = 3,\n      \"H\" = 2,\n      \"I\" = 1,\n      .default = NA_real_\n    )\n  )\n#remove NA in primary dataset features\nopa_clean <- opa_res_date %>%\n  drop_na(\n    sale_price,\n    year_built,\n    total_livable_area,\n    number_of_bedrooms,\n    number_of_bathrooms,\n    interior_condition,\n    exterior_condition,\n    garage_spaces,\n    fireplaces,\n    basement_score,\n    census_tract,\n    market_value\n  )\n\n#construct opa_clean with all relative columns\nopa_clean <- opa_clean %>%\n  select(\n    sale_price,\n    sale_date,\n    year_built,\n    total_livable_area,\n    number_of_bedrooms,\n    number_of_bathrooms,\n    interior_condition,\n    exterior_condition,\n    garage_spaces,\n    fireplaces,\n    basement_score,\n    census_tract,\n    market_value\n  )%>%\n  filter(sale_price >= 1000) %>% #obvious error 1: there are some sale prices equal to 0,1,10 so I filter them out\n  filter(number_of_bathrooms >0) #obvious error 2 (assumption): Observations with zero bathrooms were removed because residential properties typically contain at least one bathroom. (but for bedroom it's OK to have 0 bedroom because it may be studio.)\n\nopa_clean <- opa_clean %>% #create new variable: calculate house age base on sale year\n  mutate(\n    house_age = year(sale_date) - as.numeric(year_built)\n  )\n```\n:::\n\n\nLoad secondary data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#select Philadelphia census tracts, convert to PA South for mapping\nphl_tracts <- tracts(state = \"PA\", county = \"Philadelphia\", cb = TRUE, year = 2022) %>%\n  st_transform(PHL_EPSG)\n\n# Pull ACS variables (2022 ACS 5-year)\nacs_vars <- c(\n  median_income    = \"B19013_001\",  # median household income\n  total_households = \"B08201_001\",  # total households\n  no_vehicle       = \"B08201_002\"   # households with 0 vehicles\n)\n\nphl_acs <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  county = \"Philadelphia\",\n  variables = acs_vars,\n  year = 2022,\n  survey = \"acs5\",\n  geometry = FALSE\n) %>%\n  select(GEOID, variable, estimate) %>%\n  pivot_wider(names_from = variable, values_from = estimate) %>%\n  mutate(\n    pct_no_vehicle = no_vehicle / total_households\n  ) %>%\n  select(GEOID, median_income, pct_no_vehicle)\n\n# join to tract geometry\nphl_tracts <- phl_tracts %>%\n  left_join(phl_acs, by = \"GEOID\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### load remote dataset\n\nCRIME_2024_URL <- \"https://phl.carto.com/api/v2/sql?filename=incidents_part1_part2&format=csv&q=SELECT%20*%20,%20ST_Y(the_geom)%20AS%20lat,%20ST_X(the_geom)%20AS%20lng%20FROM%20incidents_part1_part2%20WHERE%20dispatch_date_time%20%3E=%20%272024-01-01%27%20AND%20dispatch_date_time%20%3C%20%272025-01-01%27\"\n\nCRIME_2023_URL <- \"https://phl.carto.com/api/v2/sql?filename=incidents_part1_part2&format=csv&q=SELECT%20*%20,%20ST_Y(the_geom)%20AS%20lat,%20ST_X(the_geom)%20AS%20lng%20FROM%20incidents_part1_part2%20WHERE%20dispatch_date_time%20%3E=%20%272023-01-01%27%20AND%20dispatch_date_time%20%3C%20%272024-01-01%27\"\n\n\nSCHOOLS_URL <- \"https://hub.arcgis.com/api/v3/datasets/d46a7e59e2c246c891fbee778759717e_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1\"\n\nPARKS_URL <- \"https://hub.arcgis.com/api/v3/datasets/d52445160ab14380a673e5849203eb64_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1\"\n\nSEPTA_URL <- \"https://hub.arcgis.com/api/v3/datasets/b227f3ddbe3e47b4bcc7b7c65ef2cef6_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1\"\n\nVACANT_URL <- \"https://hub.arcgis.com/api/v3/datasets/f7ed68293c5e40d58f1de9c8435c3e84_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1\"\n\n#combine crime 2023 and 2024 to crime_all\ncrime2024 <- read_csv(CRIME_2024_URL, show_col_types = FALSE)\ncrime2023 <- read_csv(CRIME_2023_URL, show_col_types = FALSE)\ncrime_all <- bind_rows(crime2023, crime2024)\n\n#read the rest of csv if you cannot run these just select lines below and rerun the selected line, took me a while to run these, rerun and rerun again and again~~~\nschools <- read_sf(SCHOOLS_URL)\nparks   <- read_sf(PARKS_URL)\nsepta   <- read_sf(SEPTA_URL)\nvacant  <- read_sf(VACANT_URL)\n```\n:::\n\n\nClean secondary data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# remove records without coordinates (only crime data has some lines without xy)\ncrime_clean <- crime_all %>%\n  filter(!is.na(lat), !is.na(lng)) %>%\n  st_as_sf(coords = c(\"lng\", \"lat\"), crs = 4326, remove = FALSE) %>%\n  st_transform(PHL_EPSG)\n\nschools_clean <- schools %>%\n  filter(!st_is_empty(geometry)) %>%\n  st_transform(PHL_EPSG)\n\nparks_clean <- parks %>%\n  filter(!st_is_empty(geometry)) %>%\n  st_transform(PHL_EPSG)\n\nsepta_clean <- septa %>%\n  filter(!st_is_empty(geometry)) %>%\n  st_transform(PHL_EPSG)\n\nvacant_clean <- vacant %>%\n  filter(!st_is_empty(geometry)) %>%\n  st_transform(PHL_EPSG)\n```\n:::\n\n\n### Data cleaning methods:\n\n**Primary Data Cleaning**\n\nProperty transactions were filtered using the recorded sale date to include only sales from 2023 to 2024, as these recent transactions better reflect current housing market trends. Each parcel was represented as a spatial geometry, and the property locations were projected into a consistent coordinate reference system so that the spatial relationships could be accurately measured. This is important because a property’s location determines the influence of its surrounding environment. The dataset was also filtered to retain only residential properties by selecting residential category code=1. Several cleaning steps were applied to improve data quality and ensure the reliability of the modeling dataset. Observations with missing values in key structural variables such as sale price, year built, total livable area, number of bedrooms, number of bathrooms, interior condition, exterior condition, garage spaces, fireplaces, basement condition, and census tract were removed to avoid incomplete records. Obvious data entry errors were also addressed. For example, transactions with sale prices equal to extremely small values, such as 0, 1, or 10 were removed because these likely represent recording errors or non-market transactions. Properties with zero bathrooms were excluded based on the assumption that residential units typically contain at least one bathroom. But we did not filter bedroom=0 because we assume this may be a studio. Additionally, basement condition categories were converted into a numerical score to make them usable in quantitative modeling. A new variable representing house age was calculated by subtracting the year built from the sale year.\n\n**Secondary Data Cleaning**\n\nSecondary datasets describing neighborhood conditions and accessibility were obtained from multiple external sources, including crime incidents, schools, parks, transit stops, and vacant properties. These datasets were first converted into spatial objects and projected into a consistent coordinate reference system so that spatial operations such as distance calculations, buffers, and spatial joins could be performed accurately. Crime data from 2023 and 2024 were combined to represent recent neighborhood safety conditions, and records without geographic coordinates were removed to ensure that all incidents could be mapped correctly. For other spatial datasets, records with empty geometries were removed to prevent errors during spatial analysis. All datasets were then transformed into the same projection system to maintain spatial consistency across layers.\n\n## Exploratory Data Analysis\n\n### 1. Histogram: Distribution of sale prices\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(opa_clean, aes(x = sale_price)) +\n  geom_histogram(fill = \"lightblue\", bins = 100) +\n  geom_vline(aes(xintercept = median(sale_price, na.rm = TRUE)),\n             color = \"grey40\", linewidth = 0.5) +\n  annotate(\"text\",\n           x = median(opa_clean$sale_price, na.rm = TRUE),\n           y = Inf,\n           vjust = 4,\n           hjust = -0.1,\n           label = paste0(\n             \"Median = $\",\n             formatC(median(opa_clean$sale_price, na.rm = TRUE),\n                     format = \"f\",\n                     big.mark = \",\",\n                     digits = 0)\n           ),\n           color = \"grey40\",\n           size = 3) +\n  labs(\n    title = \"Distribution of Philadelphia Home Sale Prices\",\n    x = \"Sale Price (USD)\",\n    y = \"Frequency\"\n  ) +\n  scale_x_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/histogram- Distribution of Sale Prices-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:**\n\nThe figure shows the distribution of Philadelphia home sale prices in 2023-2024. The distribution is extremely right-skewed, meaning that a small number of very high-priced luxury property sales pull the distribution toward the right. Some sale prices exceed \\$6,000,000, which likely represent luxury Center City condominiums and large historic houses.\n\nHowever, most sale prices are clustered between \\$50,000 and \\$500,000. This phenomenon indicates that the majority of homes fall within this price range, representing the core housing market in Philadelphia. More specifically, there is a large concentration of homes priced between \\$100,000 and \\$300,000. These prices typically correspond to rowhouses, older urban housing stock, and smaller single-family homes. This pattern reflects that Philadelphia has a substantial portion of housing stock that remains relatively affordable compared with many other major U.S. cities.\n\nThe median sale price is \\$240,000, meaning that half of the properties sold for less than \\$240,000 and half sold for more. Because the median is not affected by extreme values, it better represents the typical residential sale price in Philadelphia.\n\nOverall, the Philadelphia housing market shows two informal price segments: a large core housing market and a much smaller luxury market.\n\n### 2. Map: Distribution of Philadelphia Home Sale Prices\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load Philadelphia neighborhood boundary\nneigh_url <- \"https://raw.githubusercontent.com/opendataphilly/open-geo-data/refs/heads/master/philadelphia-neighborhoods/philadelphia-neighborhoods.geojson\"\n\nneigh <- sf::read_sf(neigh_url)\n\n# Match CRS with property data\nneigh <- st_transform(neigh, st_crs(opa_clean))\n\nopa_sf <- st_as_sf(\n  opa_clean,\n  coords = c(\"longitude\", \"latitude\"),   \n  crs = 4326,\n  remove = FALSE\n) %>%\n  st_transform(st_crs(phl_tracts))\n\n# Map\np_price_map <- ggplot() +\n  geom_sf(\n    data = neigh,\n    fill = NA,\n    color = \"grey75\",\n    linewidth = 0.25\n  ) +\n  geom_sf(\n    data = opa_sf,\n    aes(color = sale_price),\n    alpha = 0.65,\n    size = 0.18\n  ) +\n  scale_color_viridis_c(\n    name   = \"Sale price (USD)\",\n    option = \"magma\",\n    direction = -1,\n    labels = scales::dollar,\n    limits = c(60000, 1200000),\n    oob    = scales::squish,\n    breaks = c(100000, 200000, 300000, 400000, 600000, 800000, 1000000, 1200000)\n  ) +\n  guides(\n    color = guide_colorbar(barheight = grid::unit(4, \"cm\"))\n  ) +\n  coord_sf() +\n  labs(\n    title    = \"Geographical Distribution of Philadelphia Home Sale Prices\",\n    subtitle = \"Each property colored by sale price\"\n  ) +\n  theme_void(base_size = 12) +\n  theme(\n    legend.position = c(0.92, 0.25),\n    plot.title      = element_text(face = \"bold\", hjust = 0),\n    plot.subtitle   = element_text(hjust = 0)\n  )\n\np_price_map\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/Distribution of Philadelphia Home Sale Prices-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:**\n\nThe figure shows the geographical distribution of Philadelphia home sale prices in 2023–2024. It indicates a very strong spatial pattern in Philadelphia’s home sale prices. The darker purple dots represent higher sale prices, while the lighter yellow dots represent lower sale prices.\n\nHigher-priced homes are highly concentrated in Center City and surrounding neighborhoods, particularly in areas near Rittenhouse Square, Society Hill, and parts of South Philadelphia close to downtown. These locations contain many properties with sale prices above \\$600,000 and up to \\$1,200,000. Another cluster of high-priced homes is in Northwest Philadelphia, where the suburban environment provides larger land parcels for single-family homes and suburban-style housing.\n\nLower-priced homes are widely distributed across North Philadelphia, West Philadelphia, and parts of Northeast Philadelphia. These areas contain a large number of homes selling for \\$100,000 to \\$300,000, which aligns with the core housing market identified in the price distribution histogram.\n\nOverall, the map shows that housing prices in Philadelphia are strongly influenced by location. This relates to how we will select urban characteristics associated with location to predict sale prices, such as neighborhood characteristics, school quality, transit access, and the importance of local amenities.\n\n### 3. Price vs. structural features\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# common theme\nbase_theme <- theme_minimal(base_size = 11) +\n  theme(\n    panel.grid.minor = element_blank(),\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n    axis.title = element_text(size = 11),\n    axis.text = element_text(size = 9)\n  )\n\n# 1) Livable area vs price (scatter + loss)\np_area <- ggplot(opa_clean, aes(x = total_livable_area, y = sale_price)) +\n  geom_point(alpha = 0.20, size = 0.7, color = \"#1f77b4\") +\n  scale_y_continuous(labels = dollar) +\n  scale_x_continuous(labels = comma) +\n  coord_cartesian(xlim = c(300, 5000), ylim = c(60000, 2000000)) +\n  labs(title = \"Price vs Livable Area\", x = \"Livable Area (sq ft)\", y = \"Sale Price\") +\n  base_theme\n\n# 2) Year built vs price (hex density + smooth on binned year)\np_year <- ggplot(\n  opa_clean %>% filter(!is.na(house_age)),\n  aes(x = house_age, y = sale_price)\n) +\n  geom_hex(bins = 35) +\n  scale_fill_viridis_c(option = \"plasma\") +\n  scale_y_continuous(labels = dollar) +\n  labs(\n    title = \"Price vs House Age (Density)\",\n    x = \"House Age at Time of Sale (years)\",\n    y = \"Sale Price\",\n    fill = \"Count\"\n  ) +\n  base_theme +\n  theme(legend.position = \"right\")\n\n# 3) Bedrooms vs price (jitter + loess)\np_bed <- ggplot(opa_clean, aes(x = number_of_bedrooms, y = sale_price)) +\n  geom_jitter(alpha = 0.18, width = 0.15, height = 0, size = 0.7, color = \"#2ca02c\") +\n  scale_y_continuous(labels = dollar) +\n  coord_cartesian(ylim = c(60000, 2000000)) +\n  labs(title = \"Price vs Bedrooms\", x = \"Bedrooms\", y = \"Sale Price\") +\n  base_theme\n\n# 4) Bathrooms vs price (jitter + loess)\np_bath <- ggplot(opa_clean, aes(x = number_of_bathrooms, y = sale_price)) +\n  geom_jitter(alpha = 0.18, width = 0.12, height = 0, size = 0.7, color = \"#9467bd\") +\n  scale_y_continuous(labels = dollar) +\n  coord_cartesian(ylim = c(60000, 2000000)) +\n  labs(title = \"Price vs Bathrooms\", x = \"Bathrooms\", y = \"Sale Price\") +\n  base_theme\n\n# combine (2x2)\n(p_area | p_year) / (p_bed | p_bath)\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/Price vs. structural features-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:**\n\n1.  The first scatter plot shows the relationship between **livable area (square feet) and sale price**. The graph reveals a strong positive relationship between housing size and sale price. As the livable area increases, the sale price generally increases as well. Most homes cluster between 800 and 2,500 square feet, with sale prices ranging roughly from \\$100,000 to \\$600,000. Larger homes above 3,000 square feet tend to command higher prices, often exceeding \\$800,000 or even \\$1,000,000, though the variation widens. The graph shows a positive relationship between livable area and price. However, it also shows that homes with similar sizes can have very different prices. There may be other factors that influence the price, such as location, neighborhood characteristics, and amenities.\n\n2.  The **Price vs House Age** density scatterplot shows the relationship between the age of a house at the time of sale and its sale price. The brighter colors indicate a higher concentration of transactions. Most homes are concentrated between about 50 and 120 years old. This shows the older rowhouses and historic building stocks in Philadelphia. Within this age range, most sale prices fall below \\$500,000, although there are still some higher-priced outliers. Homes that are very new or very old appear less frequently in the dataset, but some of them command higher sale prices than others, so the fluctuation in age and sale prices does not yield a clear pattern.\n\n3.  The **Price vs Bedrooms** scatterplot shows the distribution of sale prices across different numbers of bedrooms. Most homes have between 2 and 5 bedrooms. Sale prices within these bedroom categories cover a wide range, although many fall below \\$500,000. Homes with 4 to 6 bedrooms show a broader range of prices and include several higher-priced properties reaching above \\$1,000,000. Properties with very high bedroom counts appear less frequently and are more dispersed in the dataset. This graph shows a generally positive relationship between the number of bedrooms and sale price, where homes with more bedrooms tend to have higher prices. However, homes with very high bedroom counts appear much less frequently in the dataset. Because these observations are rare, the pattern in the higher bedroom categories appears to show a slight decreasing trend.\n\n4.  The **Price vs Bathrooms** scatterplot shows the distribution of sale prices across different numbers of bathrooms. Most properties have between 1 and 3 bathrooms. Sale prices within these categories range widely, though many remain below \\$600,000. Homes with 3 or more bathrooms appear less frequently but include a larger number of higher-priced properties. This graph indicates a generally positive relationship between the number of bathrooms and sale price, where homes with more bathrooms tend to be associated with higher prices. However, properties with very high bathroom counts appear much less frequently in the dataset. Because these observations are relatively rare, the pattern among the higher bathroom categories shows a slight decreasing trend.\n\n### 4. price vs spatial features\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1) join census variables to each sale point (income + no vehicle)\nopa_plot <- st_join(\n  opa_sf,\n  phl_tracts[, c(\"median_income\", \"pct_no_vehicle\")]\n)\n\n# 2) create spatial distance features (meters)\n# distance to nearest park\nidx_park <- st_nearest_feature(opa_plot, parks_clean)\nopa_plot$dist_park <- as.numeric(st_distance(opa_plot, parks_clean[idx_park, ], by_element = TRUE))\n\n# distance to nearest SEPTA stop\nidx_stop <- st_nearest_feature(opa_plot, septa_clean)\nopa_plot$dist_septa <- as.numeric(st_distance(opa_plot, septa_clean[idx_stop, ], by_element = TRUE))\n\n# (optional) drop geometry for faster plotting\nopa_plot_df <- opa_plot %>% st_drop_geometry()\n\n\n# Plot 1: Price vs Median Income\np_income <- ggplot(opa_plot_df, aes(x = median_income, y = sale_price)) +\n  geom_point(alpha = 0.22, size = 0.7, color = \"#1f77b4\") +\n  scale_x_continuous(labels = dollar) +\n  scale_y_continuous(labels = dollar) +\n  labs(title = \"Price vs Median Income\",\n       x = \"Median Household Income (USD)\",\n       y = \"Sale Price (USD)\") +\n  base_theme\n\n# Plot 2: Price vs % No Vehicle\np_vehicle <- ggplot(opa_plot_df, aes(x = pct_no_vehicle, y = sale_price)) +\n  geom_point(alpha = 0.22, size = 0.7, color = \"#2ca02c\") +\n  scale_y_continuous(labels = dollar) +\n  labs(title = \"Price vs % Households Without Vehicle\",\n       x = \"% No Vehicle (ACS)\",\n       y = \"Sale Price (USD)\") +\n  base_theme\n\n# Plot 3: Price vs Distance to Park\np_park <- ggplot(opa_plot_df, aes(x = dist_park, y = sale_price)) +\n  geom_point(alpha = 0.22, size = 0.7, color = \"#9467bd\") +\n  scale_x_continuous(labels = comma) +\n  scale_y_continuous(labels = dollar) +\n  labs(title = \"Price vs Distance to Nearest Park\",\n       x = \"Distance to Park (meters)\",\n       y = \"Sale Price (USD)\") +\n  base_theme\n\n# Plot 4: Price vs Distance to SEPTA Stop\np_transit <- ggplot(opa_plot_df, aes(x = dist_septa, y = sale_price)) +\n  geom_point(alpha = 0.22, size = 0.7, color = \"#17becf\") +\n  scale_x_continuous(labels = comma) +\n  scale_y_continuous(labels = dollar) +\n  labs(title = \"Price vs Distance to Nearest SEPTA Stop\",\n       x = \"Distance to Transit Stop (meters)\",\n       y = \"Sale Price (USD)\") +\n  base_theme\n\n# 3) combine into one 2x2 figure\n(p_income | p_vehicle) / (p_park | p_transit)\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/price vs spatial features-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:**\n\n1.  The **Price vs Median Income** scatterplot shows the distribution of sale prices across neighborhoods with different median household income levels. Most properties are located in areas where the median household income ranges between \\$30,000 and \\$120,000. Sale prices within these income levels vary widely, although many properties remain below \\$600,000. Higher income areas include a larger number of higher-priced homes, including several properties above \\$1,000,000. This graph indicates a generally positive relationship between neighborhood income level and housing price, where homes in higher income areas tend to have higher sale prices.\n\n2.  The **Price vs % Households With No Vehicle** scatterplot shows the distribution of sale prices across areas with different levels of car ownership. Most properties are located in areas where between 10% and 60% of households do not own a vehicle. Sale prices within these areas vary widely, though many remain below \\$600,000. Areas with very high percentages of households without vehicles appear less frequently in the dataset. The overall pattern suggests that homes are distributed across a wide range of transportation conditions, with sale prices varying across different levels of vehicle ownership.\n\n3.  The **Price vs Distance to Nearest Park** scatterplot shows the distribution of sale prices at different distances from parks. Most properties are located within approximately 0 to 600 meters of a park. Sale prices within this distance range vary widely, although many homes fall below \\$500,000. Properties located very far from parks appear less frequently in the dataset. This graph indicates a negative relationship between distance to parks and housing price, where homes closer to parks tend to be associated with higher sale prices.\n\n4.  The **Price vs Distance to Nearest Transit Stop** scatterplot shows the distribution of sale prices across different distances from public transit stops. Most homes are located within approximately 0 to 500 meters of a transit stop. Sale prices within this distance range vary widely, though many remain below \\$600,000. Properties located farther from transit stops appear less frequently. This graph indicates a negative relationship between distance to transit and housing price, where homes closer to transit access tend to be associated with higher prices.\n\n### 5. Creative plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# -----------------------------\n# 1. make sure property data is sf and projected\n# -----------------------------\nopa_pts <- opa_clean %>%\n  st_as_sf() %>% \n  st_transform(PHL_EPSG)\n\n# -----------------------------\n# 2. build Philadelphia boundary from census tracts\n# -----------------------------\nphl_boundary <- phl_tracts %>%\n  summarise() %>%\n  st_make_valid()\n\n# -----------------------------\n# 3. create fishnet\n# you can try 800, 1000, or 1200 meters\n# -----------------------------\ncell_size <- 1000\n\nfishnet <- st_make_grid(\n  phl_boundary,\n  cellsize = cell_size,\n  square = TRUE\n) %>%\n  st_as_sf() %>%\n  st_intersection(phl_boundary) %>%\n  mutate(grid_id = row_number())\n\n# -----------------------------\n# 4. spatial join properties to fishnet\n# -----------------------------\ngrid_sales <- fishnet %>%\n  st_join(opa_pts, join = st_intersects)\n\n# -----------------------------\n# 5. aggregate sale prices by grid\n# use median price + count\n# -----------------------------\ngrid_summary <- grid_sales %>%\n  st_drop_geometry() %>%\n  group_by(grid_id) %>%\n  summarise(\n    n_sales = n(),\n    med_price = median(sale_price, na.rm = TRUE),\n    mean_price = mean(sale_price, na.rm = TRUE)\n  )\n\nfishnet_price <- fishnet %>%\n  left_join(grid_summary, by = \"grid_id\") %>%\n  mutate(\n    n_sales = replace_na(n_sales, 0)\n  )\n\n# keep only cells with enough observations\n# usually >= 5 is safer\nfishnet_valid <- fishnet_price %>%\n  filter(n_sales >= 5, !is.na(med_price))\n\n# -----------------------------\n# 6. create spatial neighbors and weights\n# -----------------------------\nnb <- st_contiguity(fishnet_valid)\nwts <- st_weights(nb)\n\nfishnet_valid <- fishnet_valid %>%\n  mutate(\n    nb = nb,\n    wts = wts\n  )\n\n# -----------------------------\n# 7. local Moran's I\n# -----------------------------\nfishnet_valid <- fishnet_valid %>%\n  mutate(local_moran = local_moran(med_price, nb, wts)) %>%\n  tidyr::unnest(local_moran)\n\n# -----------------------------\n# 8. spatial lag and quadrant classification\n# -----------------------------\n\nlistw <- nb2listw(nb, style = \"W\", zero.policy = TRUE)\n\n# spatial lag\nfishnet_valid$lag_price <- lag.listw(\n  listw,\n  fishnet_valid$med_price,\n  zero.policy = TRUE\n)\n\nfishnet_valid <- fishnet_valid %>%\n  mutate(\n    price_std = as.numeric(scale(med_price)),\n    lag_std   = as.numeric(scale(lag_price)),\n    lisa_cat = case_when(\n      p_ii <= 0.05 & price_std >= 0 & lag_std >= 0 ~ \"HH\",\n      p_ii <= 0.05 & price_std <= 0 & lag_std <= 0 ~ \"LL\",\n      p_ii <= 0.05 & price_std >= 0 & lag_std <= 0 ~ \"HL\",\n      p_ii <= 0.05 & price_std <= 0 & lag_std >= 0 ~ \"LH\",\n      TRUE ~ \"Not significant\"\n    )\n  )\n\nneigh_url <- \"https://raw.githubusercontent.com/opendataphilly/open-geo-data/refs/heads/master/philadelphia-neighborhoods/philadelphia-neighborhoods.geojson\"\nneigh <- read_sf(neigh_url) %>%\n  st_transform(PHL_EPSG)\n\n# color palette\nlisa_cols <- c(\n  \"HH\" = \"#d73027\",              # hot spot\n  \"LL\" = \"#4575b4\",              # cold spot\n  \"HL\" = \"#f46d43\",              # high surrounded by low\n  \"LH\" = \"#74add1\",              # low surrounded by high\n  \"Not significant\" = \"grey90\"\n)\n\nggplot() +\n  geom_sf(data = phl_boundary, fill = \"grey98\", color = NA) +\n  geom_sf(\n    data = fishnet_valid,\n    aes(fill = lisa_cat),\n    color = \"white\",\n    linewidth = 0.12\n  ) +\n  geom_sf(\n    data = neigh,\n    fill = NA,\n    color = alpha(\"grey30\", 0.35),\n    linewidth = 0.18\n  ) +\n  scale_fill_manual(\n    values = lisa_cols,\n    drop = FALSE,\n    name = \"LISA cluster\"\n  ) +\n  labs(\n    title = \"Philadelphia Housing Price Clusters\",\n    subtitle = \"Fishnet-based Local Moran's I classification of median sale price (2023–2024)\",\n    caption = \"HH = high-high, LL = low-low, HL = high-low, LH = low-high | cells with fewer than 5 sales excluded\"\n  ) +\n  theme_void(base_size = 13) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, hjust = 0),\n    plot.subtitle = element_text(size = 11, color = \"grey30\", hjust = 0),\n    plot.caption = element_text(size = 7, color = \"grey40\"),\n    legend.position = \"right\",\n    legend.title = element_text(face = \"bold\"),\n    panel.background = element_rect(fill = \"#f8f8f8\", color = NA),\n    plot.background = element_rect(fill = \"#f8f8f8\", color = NA)\n  )\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/creative visual-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:**\n\nThe LISA map shows the spatial clustering of median housing sale prices across Philadelphia using a fishnet grid and Local Moran’s I analysis. Each grid cell represents the median sale price of properties within that area, and only cells containing at least five transactions were included to ensure statistical reliability. Red cells represent High–High clusters, where areas with high housing prices are surrounded by neighboring areas that also have high prices. These clusters appear mainly in Center City and parts of Northwest Philadelphia. Dark blue cells represent Low–Low clusters, where areas with lower housing prices are surrounded by other low-priced areas. These clusters are primarily in North Philadelphia. Light blue cells represent Low–High outliers, which are lower-priced areas located near higher-priced neighborhoods. It is at the periphery of Center City. Grey cells indicate locations where the spatial pattern of housing prices is not statistically significant. Overall, the map shows that housing prices in Philadelphia exhibit clear spatial clustering.\n\n## Feature Engineering\n\nSeveral spatial variables were constructed to capture neighborhood conditions and accessibility that may influence housing prices.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Number of crime incidents within 400m of each property\ncrime_buffer <- st_buffer(opa_sf, 400)\n\ncrime_count <- lengths(\n  st_intersects(crime_buffer, crime_clean)\n)\n\nopa_sf$crime_400m <- crime_count\n\nsummary(opa_sf$crime_400m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    1.0   435.0   744.0   775.5   987.0  4295.0 \n```\n\n\n:::\n:::\n\n\nCrime exposure was measured using police incident data from 2023 and 2024. For each property, the number of reported crime incidents occurring within a 400-meter buffer was calculated. This buffer represents the immediate walkable neighborhood environment surrounding the property and captures local safety conditions that may affect housing demand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- 3\n\npark_dist_matrix <- st_distance(opa_sf, parks_clean)\n\npark_dist_matrix <- as.matrix(park_dist_matrix)\n\nopa_sf$knn_park_dist <- apply(park_dist_matrix, 1, function(x){\n  mean(sort(x)[1:k])\n})\n\nsummary(opa_sf$knn_park_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  29.42  305.31  407.81  447.03  536.28 1879.25 \n```\n\n\n:::\n:::\n\n\nAccess to green space was measured using a K-Nearest Neighbor (KNN) approach with k = 3, calculating the distance from each property to the three nearest major parks. This variable captures the availability of nearby recreational and environmental amenities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool_dist_matrix <- st_distance(opa_sf, schools_clean)\n\nschool_dist_matrix <- as.matrix(school_dist_matrix)\n\nk <- 3\n\nopa_sf$knn_school_dist <- apply(\n  school_dist_matrix,\n  1,\n  function(x, k) {\n    mean(sort(x)[1:k])\n  },\n  k = k\n)\nsummary(opa_sf$knn_school_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  91.76  373.14  491.96  529.32  646.85 2429.12 \n```\n\n\n:::\n:::\n\n\nAccessibility to essential services was also considered. School accessibility was measured using a KNN method that calculates the distance to the three nearest schools.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# nearest SEPTA stop for each property\nnearest_stop <- st_nearest_feature(opa_sf, septa_clean)\n\n# distance (meters)\nopa_sf$dist_septa <- as.numeric(\n  st_distance(\n    opa_sf,\n    septa_clean[nearest_stop, ],\n    by_element = TRUE\n  )\n)\nsummary(opa_sf$dist_septa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n   6.223   68.398  104.441  133.962  172.067 1268.155 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#closer to transit+people access to 0 vehicle more= higher transit_x_no_vehicle value\nopa_sf <- st_join(\n  opa_sf,\n  phl_tracts[, c(\"median_income\", \"pct_no_vehicle\")]\n)\n\n# Define transit access index from distance to SEPTA\nopa_sf$transit_access <- 1 / (opa_sf$dist_septa + 1)\n\n# Transit access × Car ownership (proxy: % households with no vehicle)\nopa_sf$transit_x_no_vehicle <- opa_sf$transit_access * opa_sf$pct_no_vehicle\n\nsummary(opa_sf$pct_no_vehicle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.01366 0.14267 0.23077 0.25583 0.35621 0.78481       8 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(opa_sf$transit_x_no_vehicle)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.000015 0.001013 0.002226 0.003108 0.004240 0.057620        8 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntracts_sf <- st_read(here(\"data\", \"Census_tracts_2010 (1).geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `db894b56-81d3-49af-9fdf-8a4f8170db4f2020328-1-1i3f5cj.8z1e' from data source `C:\\Users\\muyan\\Documents\\UPenn Files\\CPLN 5920\\CPLN-5920-Portfolio\\data\\Census_Tracts_2010 (1).geojson' \n  using driver `GeoJSON'\nSimple feature collection with 384 features and 14 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -75.28031 ymin: 39.86747 xmax: -74.95575 ymax: 40.13793\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ntracts_sf <- st_transform(tracts_sf, st_crs(opa_sf))\nopa_sf <- st_join(opa_sf, tracts_sf[\"GEOID10\"])\n```\n:::\n\n\nTransit accessibility was represented by calculating the Euclidean distance from each property to the nearest transit stop. Shorter distances indicate better access to public transportation, which can increase the convenience and desirability of a property. The interactive feature of transit accessibility and car ownership is calculated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create 300m buffer around each property\nvacant_buffer <- st_buffer(opa_sf, 300)\n\n# count vacant properties within buffer\nvacant_count <- lengths(\n  st_intersects(vacant_buffer, vacant_clean)\n)\n\n# add feature to datasets\nopa_sf$vacant_300m <- vacant_count\n\nsummary(opa_sf$vacant_300m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    0.0     3.0     9.0    14.9    21.0   118.0 \n```\n\n\n:::\n:::\n\n\nFinally, neighborhood physical conditions were represented by calculating the number of vacant properties within a 300-meter buffer around each home using the city’s vacant property dataset. Higher concentrations of vacant properties may indicate neighborhood disinvestment and can negatively influence surrounding property values.\n\n## Model building\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1) modeling table (drop geometry)\nmodel_df <- opa_sf %>% st_drop_geometry()\n\n# 2) full set of variables used across ALL models\nfull_cols <- c(\n  \"sale_price\",\n  \"total_livable_area\",\"number_of_bedrooms\",\"number_of_bathrooms\",\"year_built\",\"market_value\",\"fireplaces\",\"crime_400m\",\"knn_school_dist\",\"knn_park_dist\",\"dist_septa\",\"vacant_300m\",\"garage_spaces\",\"interior_condition\",\"census_tract\",\"exterior_condition\",\"median_income\",\"pct_no_vehicle\",\"transit_x_no_vehicle\"\n)\npa_tracts <- tracts(state = \"PA\", year = 2023)\n\nphilly_tracts <- pa_tracts %>%\n  filter(COUNTYFP == \"101\")\n\nphilly_tracts <- st_transform(philly_tracts, st_crs(opa_sf))\n\nopa_sf <- st_join(opa_sf, philly_tracts[\"GEOID\"])\n\n# 3) keep only these columns + drop NA once\nmodel_df <- model_df %>%\n  select(all_of(full_cols)) %>%\n  filter(complete.cases(.))\n\n#Create age\nmodel_df$year_built <- as.numeric(model_df$year_built)\nmodel_df <- model_df %>%\n  mutate(\n    age = 2024 - year_built\n  )\nmodel_df <- model_df %>%\n  mutate(\n    age_sq = age^2\n  )\n\nopa_sf <- opa_sf %>%\n  mutate(age = 2024 - as.numeric(year_built))\n\n# --- Center City point (City Hall) ---\ncenter_city <- st_sfc(st_point(c(-75.1636, 39.9526)), crs = 4326)\n\n# Make CRS match opa_sf (so distance is in meters/feet depending on your CRS)\ncenter_city <- st_transform(center_city, st_crs(opa_sf))\n\n# --- Distance to Center City (for each property) ---\nopa_sf$dist_center <- as.numeric(st_distance(opa_sf, center_city))\n\n# Squared distance term (non-linear)\nopa_sf$dist_center_sq <- opa_sf$dist_center^2\n\n# Rebuild model_df including the new variables\nmodel_df <- opa_sf %>%\n  st_drop_geometry() %>%\n  select(\n    sale_price,\n    total_livable_area, number_of_bedrooms, number_of_bathrooms, year_built,\n    crime_400m, knn_school_dist, knn_park_dist, dist_septa,     vacant_300m,garage_spaces,fireplaces,interior_condition,age,census_tract,\n    median_income, pct_no_vehicle,\n    dist_center, dist_center_sq\n  ) %>%\n  filter(complete.cases(.))\n\n# calculate cutoffs\nlower_cut <- quantile(model_df$sale_price, 0.01, na.rm = TRUE)\nupper_cut <- quantile(model_df$sale_price, 0.99, na.rm = TRUE)\n\n# remove top 5% and bottom 5%\nmodel_df <- model_df %>%\n  filter(sale_price >= lower_cut,\n         sale_price <= upper_cut)\n\n#final data cleaning\nmodel_df <- model_df %>%\n  filter(complete.cases(.))\n# optional: quick check\nnrow(model_df)\n```\n:::\n\nTo prepare the data for model estimation, the spatial geometry was first removed from the property dataset so that the remaining file could be used as a standard tabular dataset for regression analysis. Only variables relevant to the modeling process were retained, including the dependent variable and selected explanatory variables used across the candidate model specifications. Observations with missing values were then removed to avoid inconsistencies in estimation and to ensure that all models were fitted on the same set of observations. This step is important because allowing different models to use different sample sizes can make performance comparisons less reliable. After cleaning and filtering, the final modeling dataset contains 18,485 residential property sales, providing a large and consistent sample for model estimation and validation.\n\n::: {.cell}\n\n```{.r .cell-code}\np1  <- quantile(model_df$sale_price, 0.01, na.rm = TRUE)\np99 <- quantile(model_df$sale_price, 0.99, na.rm = TRUE)\n\nggplot(model_df, aes(x = sale_price)) +\n  geom_histogram(bins = 80, fill = \"lightblue\", color = \"white\") +\n  \n  geom_vline(xintercept = p1, color = \"red\", linetype = \"dashed\", linewidth = 1) +\n  geom_vline(xintercept = p99, color = \"red\", linetype = \"dashed\", linewidth = 1) +\n  \n  \n  labs(\n    title = \"Distribution of Philadelphia Home Sale Prices\",\n    subtitle = \"Red dashed lines indicate bottom and top 1% of sales\",\n    x = \"Sale Price (USD)\",\n    y = \"Frequency\"\n  ) +\n  scale_x_continuous(labels = scales::dollar) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\nThe distribution of home sale prices is right-skewed, with a small number of extremely high-value properties extending the upper tail of the distribution. These extreme observations can disproportionately influence regression estimates and reduce model stability. To reduce the impact of these outliers, observations below the 1st percentile and above the 99th percentile of sale prices were removed. This trimming removes extreme market anomalies while retaining the vast majority of typical housing transactions.Although this approach excludes a portion of observations and therefore does not represent the full range of market outcomes, but it improves model stability and allows the regression to better capture the relationships present in the typical housing market.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif_check <- lm(\n  sale_price ~     total_livable_area + \n    number_of_bedrooms +\n    number_of_bathrooms +\n    garage_spaces +\n    fireplaces +\n    interior_condition +\n    crime_400m +                  #Spatial\n    knn_school_dist +             #Spatial\n    knn_park_dist +               #Spatial\n    dist_septa +                  #Spatial\n    vacant_300m +                 #Spatial\n    median_income +               #Census variables\n    pct_no_vehicle +              #Census variables\n    dist_center ,                 #Spatial(non-linear)\n  data = model_df\n)\n\nvif(vif_check)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                        GVIF Df GVIF^(1/(2*Df))\ntotal_livable_area  2.624138  1        1.619919\nnumber_of_bedrooms  1.827386  1        1.351808\nnumber_of_bathrooms 1.742442  1        1.320016\ngarage_spaces       1.518186  1        1.232147\nfireplaces          1.216415  1        1.102912\ninterior_condition  1.456209  7        1.027209\ncrime_400m          2.353212  1        1.534018\nknn_school_dist     1.640401  1        1.280782\nknn_park_dist       1.341647  1        1.158295\ndist_septa          1.229931  1        1.109022\nvacant_300m         2.405394  1        1.550933\nmedian_income       2.354925  1        1.534576\npct_no_vehicle      2.821950  1        1.679866\ndist_center         2.880006  1        1.697058\n```\n\n\n:::\n:::\n\n\nThe variance inflation factor (VIF) results suggest that multicollinearity is not a major concern in this model. All variables have relatively low VIF values, with the highest values remaining well below commonly used thresholds of concern such as 5 or 10. Most predictors fall close to 1 to 3, indicating that the explanatory variables are not overly redundant with one another. This means that the model is able to estimate the independent effect of each variable without serious distortion caused by strong linear relationships among predictors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 1: Structural\nm1 <- lm(\n  sale_price ~\n    total_livable_area +\n    number_of_bedrooms +\n    number_of_bathrooms +\n    garage_spaces +\n    fireplaces +\n    interior_condition +\n    age + I(age^2) ,\n  data = model_df\n)\n\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + garage_spaces + fireplaces + interior_condition + \n    age + I(age^2), data = model_df)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1008572   -76853   -14113    57153  1252447 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          2.475e+05  1.083e+04  22.851  < 2e-16 ***\ntotal_livable_area   1.860e+02  3.217e+00  57.821  < 2e-16 ***\nnumber_of_bedrooms  -3.649e+04  1.849e+03 -19.729  < 2e-16 ***\nnumber_of_bathrooms  6.074e+04  2.042e+03  29.748  < 2e-16 ***\ngarage_spaces        1.243e+04  2.155e+03   5.770 8.07e-09 ***\nfireplaces           7.268e+04  3.615e+03  20.108  < 2e-16 ***\ninterior_condition2  8.856e+03  1.094e+04   0.809 0.418250    \ninterior_condition3  3.883e+04  1.048e+04   3.705 0.000212 ***\ninterior_condition4 -4.556e+04  1.069e+04  -4.263 2.03e-05 ***\ninterior_condition5 -5.166e+04  1.551e+04  -3.332 0.000865 ***\ninterior_condition6 -1.748e+05  2.457e+04  -7.113 1.18e-12 ***\ninterior_condition7 -1.631e+05  2.294e+04  -7.109 1.22e-12 ***\ninterior_condition8 -1.026e+05  1.364e+05  -0.752 0.451906    \nage                 -4.203e+03  1.226e+02 -34.274  < 2e-16 ***\nI(age^2)             2.231e+01  6.450e-01  34.585  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 136000 on 18470 degrees of freedom\nMultiple R-squared:  0.5557,\tAdjusted R-squared:  0.5554 \nF-statistic:  1650 on 14 and 18470 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nFor the first model, a baseline structural hedonic regression was estimated using only property-level housing characteristics. The model predicts residential sale price as a function of total livable area, number of bedrooms, number of bathrooms, garage spaces, fireplaces, interior condition, and housing age. A quadratic term for age, age², was also included to capture a possible non-linear relationship between property age and sale price, since the effect of age may not be constant across all homes. This first specification was designed to measure how much variation in sale price can be explained by the physical and structural features of the house alone, before adding neighborhood, accessibility, or other spatial variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 2: + Spatial + Socioeconomic\nm2 <- lm(\n  sale_price ~\n    total_livable_area + \n    number_of_bedrooms +\n    number_of_bathrooms +\n    garage_spaces +\n    fireplaces +\n    interior_condition +\n    age + I(age^2) +\n    crime_400m +                  #Spatial\n    knn_school_dist +             #Spatial\n    knn_park_dist +               #Spatial\n    dist_septa +                  #Spatial\n    vacant_300m +                 #Spatial\n    median_income +               #Census variables\n    pct_no_vehicle,               #Census variables\n  data = model_df\n)\n\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + garage_spaces + fireplaces + interior_condition + \n    age + I(age^2) + crime_400m + knn_school_dist + knn_park_dist + \n    dist_septa + vacant_300m + median_income + pct_no_vehicle, \n    data = model_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-760630  -53644   -5140   42245 1321797 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         -2.070e+02  1.108e+04  -0.019 0.985086    \ntotal_livable_area   1.388e+02  2.754e+00  50.412  < 2e-16 ***\nnumber_of_bedrooms  -1.096e+04  1.579e+03  -6.940 4.04e-12 ***\nnumber_of_bathrooms  4.757e+04  1.722e+03  27.632  < 2e-16 ***\ngarage_spaces        2.105e+04  1.971e+03  10.675  < 2e-16 ***\nfireplaces           5.534e+04  3.043e+03  18.187  < 2e-16 ***\ninterior_condition2 -3.170e+04  9.231e+03  -3.434 0.000596 ***\ninterior_condition3 -3.184e+04  8.872e+03  -3.589 0.000333 ***\ninterior_condition4 -9.095e+04  9.054e+03 -10.046  < 2e-16 ***\ninterior_condition5 -5.762e+04  1.301e+04  -4.429 9.54e-06 ***\ninterior_condition6 -1.830e+05  2.060e+04  -8.883  < 2e-16 ***\ninterior_condition7 -1.625e+05  1.923e+04  -8.452  < 2e-16 ***\ninterior_condition8 -2.987e+05  1.143e+05  -2.614 0.008960 ** \nage                 -2.259e+03  1.052e+02 -21.468  < 2e-16 ***\nI(age^2)             1.212e+01  5.564e-01  21.778  < 2e-16 ***\ncrime_400m           5.427e+00  2.553e+00   2.126 0.033522 *  \nknn_school_dist      5.861e+00  4.587e+00   1.278 0.201336    \nknn_park_dist       -1.878e+01  4.408e+00  -4.259 2.06e-05 ***\ndist_septa          -1.693e+01  9.550e+00  -1.773 0.076221 .  \nvacant_300m         -1.611e+03  7.778e+01 -20.707  < 2e-16 ***\nmedian_income        2.895e+00  4.220e-02  68.620  < 2e-16 ***\npct_no_vehicle       2.156e+05  9.253e+03  23.300  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 113800 on 18463 degrees of freedom\nMultiple R-squared:  0.6887,\tAdjusted R-squared:  0.6884 \nF-statistic:  1946 on 21 and 18463 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nFor the second model, the model was expanded by adding neighborhood and location-based variables. In addition to the housing characteristics included in Model 1, this specification incorporates spatial accessibility measures and socioeconomic context variables. The added spatial variables include crime within 400 meters, distance to the nearest school, distance to the nearest park, distance to the nearest SEPTA access point, and nearby vacancy within 300 meters. Two census-based neighborhood variables, median income and the share of households without a vehicle, were also included. This second model was designed to test whether sale prices can be better explained when both property characteristics and surrounding neighborhood conditions are considered together.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model 3: + Non-linear term\nm3 <- lm(\n  sale_price ~\n    total_livable_area + \n    number_of_bedrooms +\n    number_of_bathrooms +\n    garage_spaces +\n    fireplaces +\n    interior_condition +\n    age + I(age^2) +\n    crime_400m +                  #Spatial\n    knn_school_dist +             #Spatial\n    knn_park_dist +               #Spatial\n    dist_septa +                  #Spatial\n    vacant_300m +                 #Spatial\n    median_income +               #Census variables\n    pct_no_vehicle +              #Census variables\n    dist_center +                 #Spatial(non-linear)\n    dist_center_sq ,              #Spatial(non-linear)\n  data = model_df\n)\n\nsummary(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + garage_spaces + fireplaces + interior_condition + \n    age + I(age^2) + crime_400m + knn_school_dist + knn_park_dist + \n    dist_septa + vacant_300m + median_income + pct_no_vehicle + \n    dist_center + dist_center_sq, data = model_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-736122  -51846   -3110   41904 1318846 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)          1.428e+05  1.192e+04  11.978  < 2e-16 ***\ntotal_livable_area   1.392e+02  2.694e+00  51.668  < 2e-16 ***\nnumber_of_bedrooms  -7.755e+03  1.550e+03  -5.004 5.67e-07 ***\nnumber_of_bathrooms  4.399e+04  1.686e+03  26.088  < 2e-16 ***\ngarage_spaces        3.029e+04  1.963e+03  15.426  < 2e-16 ***\nfireplaces           6.156e+04  2.980e+03  20.658  < 2e-16 ***\ninterior_condition2 -3.016e+04  9.118e+03  -3.308 0.000941 ***\ninterior_condition3 -3.088e+04  8.750e+03  -3.529 0.000419 ***\ninterior_condition4 -8.669e+04  8.969e+03  -9.666  < 2e-16 ***\ninterior_condition5 -5.321e+04  1.279e+04  -4.160 3.19e-05 ***\ninterior_condition6 -1.874e+05  2.016e+04  -9.297  < 2e-16 ***\ninterior_condition7 -1.610e+05  1.884e+04  -8.546  < 2e-16 ***\ninterior_condition8 -3.136e+05  1.116e+05  -2.810 0.004964 ** \nage                 -1.934e+03  1.046e+02 -18.495  < 2e-16 ***\nI(age^2)             1.044e+01  5.475e-01  19.077  < 2e-16 ***\ncrime_400m           2.155e-01  2.521e+00   0.085 0.931879    \nknn_school_dist      1.883e+01  4.674e+00   4.029 5.62e-05 ***\nknn_park_dist       -1.794e+00  4.408e+00  -0.407 0.684014    \ndist_septa           2.234e+01  9.510e+00   2.349 0.018814 *  \nvacant_300m         -1.615e+03  7.598e+01 -21.257  < 2e-16 ***\nmedian_income        2.158e+00  4.897e-02  44.070  < 2e-16 ***\npct_no_vehicle       9.501e+04  1.044e+04   9.104  < 2e-16 ***\ndist_center         -2.241e+01  7.545e-01 -29.704  < 2e-16 ***\ndist_center_sq       8.465e-04  2.964e-05  28.561  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 111200 on 18461 degrees of freedom\nMultiple R-squared:  0.703,\tAdjusted R-squared:  0.7027 \nF-statistic:  1900 on 23 and 18461 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nFor the third model, the second specification was further expanded by adding a non-linear location effect related to distance from Center City. In addition to the structural, spatial, and socioeconomic variables already included in Model 2, this model adds both dist_center and its squared term, dist_center_sq, to capture a curved rather than strictly linear relationship between centrality and housing prices. This allows the model to reflect the possibility that the effect of distance to the city center changes across space, rather than increasing or decreasing at a constant rate. The purpose of Model 3 was to test whether incorporating this non-linear spatial pattern could improve the model’s ability to explain variation in residential sale prices.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model 4: Interaction\nm4 <- lm(\n  sale_price ~\n    total_livable_area + \n    number_of_bedrooms +\n    number_of_bathrooms +\n    garage_spaces +\n    fireplaces +\n    interior_condition +\n    age + I(age^2) +\n    crime_400m +                  #Spatial\n    knn_school_dist +             #Spatial\n    knn_park_dist +               #Spatial\n    dist_septa +                  #Spatial\n    vacant_300m +                 #Spatial\n    median_income +               #Census variables\n    pct_no_vehicle +              #Census variables\n    dist_center +                 #Spatial(non-linear)\n    dist_center_sq +              #Spatial(non-linear)\n    dist_septa * pct_no_vehicle,  #Interaction\n  data = model_df\n)\n\nsummary(m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + garage_spaces + fireplaces + interior_condition + \n    age + I(age^2) + crime_400m + knn_school_dist + knn_park_dist + \n    dist_septa + vacant_300m + median_income + pct_no_vehicle + \n    dist_center + dist_center_sq + dist_septa * pct_no_vehicle, \n    data = model_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-732325  -51897   -3128   42342 1319921 \n\nCoefficients:\n                            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                1.327e+05  1.200e+04  11.059  < 2e-16 ***\ntotal_livable_area         1.386e+02  2.692e+00  51.494  < 2e-16 ***\nnumber_of_bedrooms        -7.883e+03  1.548e+03  -5.092 3.57e-07 ***\nnumber_of_bathrooms        4.392e+04  1.684e+03  26.076  < 2e-16 ***\ngarage_spaces              2.993e+04  1.961e+03  15.261  < 2e-16 ***\nfireplaces                 6.071e+04  2.979e+03  20.379  < 2e-16 ***\ninterior_condition2       -3.096e+04  9.107e+03  -3.400 0.000676 ***\ninterior_condition3       -3.157e+04  8.740e+03  -3.612 0.000305 ***\ninterior_condition4       -8.762e+04  8.959e+03  -9.780  < 2e-16 ***\ninterior_condition5       -5.468e+04  1.278e+04  -4.280 1.88e-05 ***\ninterior_condition6       -1.881e+05  2.014e+04  -9.339  < 2e-16 ***\ninterior_condition7       -1.624e+05  1.882e+04  -8.632  < 2e-16 ***\ninterior_condition8       -3.064e+05  1.115e+05  -2.748 0.005994 ** \nage                       -1.926e+03  1.045e+02 -18.437  < 2e-16 ***\nI(age^2)                   1.040e+01  5.469e-01  19.009  < 2e-16 ***\ncrime_400m                -7.664e-01  2.522e+00  -0.304 0.761263    \nknn_school_dist            1.595e+01  4.687e+00   3.403 0.000668 ***\nknn_park_dist             -4.766e-01  4.406e+00  -0.108 0.913862    \ndist_septa                 1.094e+02  1.587e+01   6.895 5.57e-12 ***\nvacant_300m               -1.603e+03  7.591e+01 -21.115  < 2e-16 ***\nmedian_income              2.154e+00  4.891e-02  44.042  < 2e-16 ***\npct_no_vehicle             1.532e+05  1.345e+04  11.393  < 2e-16 ***\ndist_center               -2.189e+01  7.575e-01 -28.893  < 2e-16 ***\ndist_center_sq             8.217e-04  2.982e-05  27.552  < 2e-16 ***\ndist_septa:pct_no_vehicle -4.769e+02  6.963e+01  -6.849 7.66e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 111100 on 18460 degrees of freedom\nMultiple R-squared:  0.7038,\tAdjusted R-squared:  0.7034 \nF-statistic:  1828 on 24 and 18460 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nFor the fourth model, the third specification was extended by adding an interaction term between distance to SEPTA and the share of households without a vehicle.The added interaction term, dist_septa * pct_no_vehicle, was included to test whether the effect of transit accessibility on housing prices varies depending on neighborhood car access. In other words, this model allows the value of being closer to SEPTA to differ across areas where more households may rely more heavily on public transportation. The purpose of Model 4 was to capture this conditional relationship and assess whether introducing an interaction between transit access and neighborhood socioeconomic conditions improves model performance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model 5: Fixed Effect\nm5 <- lm(\n  sale_price ~\n    total_livable_area + \n    number_of_bedrooms +\n    number_of_bathrooms +\n    garage_spaces +\n    fireplaces +\n    interior_condition +\n    age + I(age^2) +\n    crime_400m +                  #Spatial\n    knn_school_dist +             #Spatial\n    knn_park_dist +               #Spatial\n    dist_septa +                  #Spatial\n    vacant_300m +                 #Spatial\n    median_income +               #Census variables\n    pct_no_vehicle +              #Census variables\n    dist_center +                 #Spatial(non-linear)\n    dist_center_sq +              #Spatial(non-linear)\n    dist_septa * pct_no_vehicle + #Interaction\n    as.factor(census_tract),      #Fixed Effect\n  data = model_df\n)\n\nsummary(m5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sale_price ~ total_livable_area + number_of_bedrooms + \n    number_of_bathrooms + garage_spaces + fireplaces + interior_condition + \n    age + I(age^2) + crime_400m + knn_school_dist + knn_park_dist + \n    dist_septa + vacant_300m + median_income + pct_no_vehicle + \n    dist_center + dist_center_sq + dist_septa * pct_no_vehicle + \n    as.factor(census_tract), data = model_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-635941  -39220     722   34518 1287669 \n\nCoefficients:\n                             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                 7.180e+05  4.184e+04  17.161  < 2e-16 ***\ntotal_livable_area          1.357e+02  2.476e+00  54.812  < 2e-16 ***\nnumber_of_bedrooms         -2.448e+03  1.402e+03  -1.745 0.080916 .  \nnumber_of_bathrooms         3.275e+04  1.510e+03  21.686  < 2e-16 ***\ngarage_spaces               2.064e+04  1.822e+03  11.327  < 2e-16 ***\nfireplaces                  3.010e+04  2.801e+03  10.747  < 2e-16 ***\ninterior_condition2        -4.464e+04  8.156e+03  -5.473 4.49e-08 ***\ninterior_condition3        -6.165e+04  7.861e+03  -7.843 4.65e-15 ***\ninterior_condition4        -1.165e+05  8.072e+03 -14.437  < 2e-16 ***\ninterior_condition5        -7.850e+04  1.133e+04  -6.929 4.37e-12 ***\ninterior_condition6        -1.844e+05  1.767e+04 -10.433  < 2e-16 ***\ninterior_condition7        -1.735e+05  1.655e+04 -10.484  < 2e-16 ***\ninterior_condition8        -2.171e+05  9.682e+04  -2.242 0.024944 *  \nage                        -1.149e+03  1.012e+02 -11.356  < 2e-16 ***\nI(age^2)                    3.534e+00  5.629e-01   6.278 3.50e-10 ***\ncrime_400m                 -1.449e+01  3.500e+00  -4.140 3.48e-05 ***\nknn_school_dist             9.996e+00  6.419e+00   1.557 0.119409    \nknn_park_dist               9.005e+00  6.761e+00   1.332 0.182905    \ndist_septa                  5.239e+01  1.596e+01   3.282 0.001032 ** \nvacant_300m                -3.992e+02  1.115e+02  -3.581 0.000343 ***\nmedian_income               4.724e-01  1.557e-01   3.035 0.002406 ** \npct_no_vehicle             -3.939e+03  2.690e+04  -0.146 0.883602    \ndist_center                -3.004e+01  5.101e+00  -5.889 3.95e-09 ***\ndist_center_sq              1.086e-03  2.121e-04   5.118 3.11e-07 ***\nas.factor(census_tract)10   3.951e+04  3.694e+04   1.069 0.284874    \nas.factor(census_tract)100 -4.177e+05  4.500e+04  -9.282  < 2e-16 ***\nas.factor(census_tract)101 -4.591e+05  4.229e+04 -10.855  < 2e-16 ***\nas.factor(census_tract)102 -4.826e+05  4.394e+04 -10.984  < 2e-16 ***\nas.factor(census_tract)103 -4.870e+05  4.238e+04 -11.492  < 2e-16 ***\nas.factor(census_tract)104 -4.920e+05  4.228e+04 -11.635  < 2e-16 ***\nas.factor(census_tract)105 -4.992e+05  4.617e+04 -10.813  < 2e-16 ***\nas.factor(census_tract)106 -4.926e+05  4.611e+04 -10.684  < 2e-16 ***\nas.factor(census_tract)107 -4.804e+05  4.369e+04 -10.995  < 2e-16 ***\nas.factor(census_tract)108 -4.875e+05  4.035e+04 -12.080  < 2e-16 ***\nas.factor(census_tract)109 -4.662e+05  4.349e+04 -10.719  < 2e-16 ***\nas.factor(census_tract)11  -1.347e+05  3.628e+04  -3.713 0.000205 ***\nas.factor(census_tract)110 -4.587e+05  4.191e+04 -10.946  < 2e-16 ***\nas.factor(census_tract)111 -4.918e+05  4.267e+04 -11.526  < 2e-16 ***\nas.factor(census_tract)112 -4.556e+05  4.220e+04 -10.798  < 2e-16 ***\nas.factor(census_tract)113 -4.422e+05  4.319e+04 -10.237  < 2e-16 ***\nas.factor(census_tract)114 -4.362e+05  4.322e+04 -10.093  < 2e-16 ***\nas.factor(census_tract)115 -4.200e+05  4.359e+04  -9.635  < 2e-16 ***\nas.factor(census_tract)117 -5.951e+05  5.305e+04 -11.218  < 2e-16 ***\nas.factor(census_tract)118 -4.435e+05  4.327e+04 -10.249  < 2e-16 ***\nas.factor(census_tract)119 -4.573e+05  4.139e+04 -11.051  < 2e-16 ***\nas.factor(census_tract)12  -9.603e+03  3.586e+04  -0.268 0.788875    \nas.factor(census_tract)120 -4.402e+05  4.691e+04  -9.385  < 2e-16 ***\nas.factor(census_tract)121 -4.299e+05  4.700e+04  -9.148  < 2e-16 ***\nas.factor(census_tract)122 -4.226e+05  4.924e+04  -8.583  < 2e-16 ***\nas.factor(census_tract)125 -2.712e+05  5.894e+04  -4.602 4.22e-06 ***\nas.factor(census_tract)13  -2.113e+05  3.529e+04  -5.989 2.15e-09 ***\nas.factor(census_tract)131 -3.169e+05  1.023e+05  -3.097 0.001957 ** \nas.factor(census_tract)132 -4.478e+05  5.052e+04  -8.864  < 2e-16 ***\nas.factor(census_tract)133 -3.535e+05  3.899e+04  -9.067  < 2e-16 ***\nas.factor(census_tract)134 -1.187e+05  3.709e+04  -3.200 0.001378 ** \nas.factor(census_tract)135 -2.916e+05  3.672e+04  -7.941 2.12e-15 ***\nas.factor(census_tract)136 -2.493e+05  3.523e+04  -7.076 1.53e-12 ***\nas.factor(census_tract)137 -4.072e+05  3.631e+04 -11.213  < 2e-16 ***\nas.factor(census_tract)138 -4.595e+05  3.848e+04 -11.940  < 2e-16 ***\nas.factor(census_tract)139 -3.731e+05  4.590e+04  -8.129 4.62e-16 ***\nas.factor(census_tract)14  -1.056e+05  3.573e+04  -2.955 0.003133 ** \nas.factor(census_tract)140 -4.818e+05  4.134e+04 -11.654  < 2e-16 ***\nas.factor(census_tract)141 -3.594e+05  5.615e+04  -6.400 1.59e-10 ***\nas.factor(census_tract)142 -3.436e+05  3.621e+04  -9.489  < 2e-16 ***\nas.factor(census_tract)143 -3.419e+05  3.819e+04  -8.951  < 2e-16 ***\nas.factor(census_tract)144 -4.186e+05  3.637e+04 -11.507  < 2e-16 ***\nas.factor(census_tract)145 -6.043e+05  6.599e+04  -9.157  < 2e-16 ***\nas.factor(census_tract)146 -4.608e+05  4.790e+04  -9.620  < 2e-16 ***\nas.factor(census_tract)147 -3.619e+05  4.886e+04  -7.406 1.36e-13 ***\nas.factor(census_tract)149 -4.882e+05  3.943e+04 -12.383  < 2e-16 ***\nas.factor(census_tract)15  -1.767e+05  3.780e+04  -4.674 2.97e-06 ***\nas.factor(census_tract)151 -5.056e+05  3.930e+04 -12.863  < 2e-16 ***\nas.factor(census_tract)152 -5.482e+05  3.913e+04 -14.009  < 2e-16 ***\nas.factor(census_tract)153 -4.288e+05  3.883e+04 -11.042  < 2e-16 ***\nas.factor(census_tract)156 -4.513e+05  4.142e+04 -10.896  < 2e-16 ***\nas.factor(census_tract)157 -3.908e+05  3.751e+04 -10.418  < 2e-16 ***\nas.factor(census_tract)158 -3.234e+05  3.610e+04  -8.959  < 2e-16 ***\nas.factor(census_tract)16  -1.671e+05  3.857e+04  -4.333 1.48e-05 ***\nas.factor(census_tract)160 -3.438e+05  3.684e+04  -9.330  < 2e-16 ***\nas.factor(census_tract)161 -3.711e+05  3.707e+04 -10.010  < 2e-16 ***\nas.factor(census_tract)162 -4.958e+05  4.249e+04 -11.668  < 2e-16 ***\nas.factor(census_tract)163 -4.868e+05  4.205e+04 -11.577  < 2e-16 ***\nas.factor(census_tract)164 -4.901e+05  4.258e+04 -11.509  < 2e-16 ***\nas.factor(census_tract)165 -5.250e+05  4.520e+04 -11.614  < 2e-16 ***\nas.factor(census_tract)166 -5.292e+05  4.995e+04 -10.595  < 2e-16 ***\nas.factor(census_tract)167 -5.009e+05  3.849e+04 -13.015  < 2e-16 ***\nas.factor(census_tract)168 -4.972e+05  4.019e+04 -12.369  < 2e-16 ***\nas.factor(census_tract)169 -5.016e+05  4.032e+04 -12.442  < 2e-16 ***\nas.factor(census_tract)17  -1.484e+05  3.792e+04  -3.914 9.13e-05 ***\nas.factor(census_tract)170 -4.889e+05  4.231e+04 -11.555  < 2e-16 ***\nas.factor(census_tract)171 -4.484e+05  4.152e+04 -10.799  < 2e-16 ***\nas.factor(census_tract)172 -4.568e+05  4.018e+04 -11.369  < 2e-16 ***\nas.factor(census_tract)173 -5.103e+05  4.168e+04 -12.241  < 2e-16 ***\nas.factor(census_tract)174 -5.211e+05  4.421e+04 -11.785  < 2e-16 ***\nas.factor(census_tract)175 -4.952e+05  4.047e+04 -12.237  < 2e-16 ***\nas.factor(census_tract)176 -4.475e+05  4.062e+04 -11.017  < 2e-16 ***\nas.factor(census_tract)177 -4.098e+05  4.158e+04  -9.858  < 2e-16 ***\nas.factor(census_tract)178 -4.279e+05  4.083e+04 -10.480  < 2e-16 ***\nas.factor(census_tract)179 -4.055e+05  3.990e+04 -10.164  < 2e-16 ***\nas.factor(census_tract)18  -2.126e+05  3.703e+04  -5.743 9.46e-09 ***\nas.factor(census_tract)180 -3.943e+05  3.888e+04 -10.141  < 2e-16 ***\nas.factor(census_tract)183 -3.745e+05  4.374e+04  -8.562  < 2e-16 ***\nas.factor(census_tract)184 -4.022e+05  4.600e+04  -8.743  < 2e-16 ***\nas.factor(census_tract)188 -4.218e+05  4.193e+04 -10.058  < 2e-16 ***\nas.factor(census_tract)19  -2.883e+05  3.622e+04  -7.959 1.83e-15 ***\nas.factor(census_tract)190 -4.273e+05  4.316e+04  -9.901  < 2e-16 ***\nas.factor(census_tract)191 -4.149e+05  4.250e+04  -9.763  < 2e-16 ***\nas.factor(census_tract)192 -4.095e+05  4.239e+04  -9.659  < 2e-16 ***\nas.factor(census_tract)195 -4.656e+05  4.164e+04 -11.183  < 2e-16 ***\nas.factor(census_tract)197 -3.848e+05  4.295e+04  -8.960  < 2e-16 ***\nas.factor(census_tract)198 -4.142e+05  4.194e+04  -9.876  < 2e-16 ***\nas.factor(census_tract)199 -5.033e+05  4.235e+04 -11.884  < 2e-16 ***\nas.factor(census_tract)2   -4.962e+05  7.616e+04  -6.515 7.44e-11 ***\nas.factor(census_tract)20  -4.543e+05  3.621e+04 -12.547  < 2e-16 ***\nas.factor(census_tract)200 -5.115e+05  4.886e+04 -10.469  < 2e-16 ***\nas.factor(census_tract)201 -5.075e+05  4.124e+04 -12.306  < 2e-16 ***\nas.factor(census_tract)202 -4.883e+05  4.188e+04 -11.660  < 2e-16 ***\nas.factor(census_tract)203 -5.054e+05  4.648e+04 -10.875  < 2e-16 ***\nas.factor(census_tract)204 -4.664e+05  4.583e+04 -10.177  < 2e-16 ***\nas.factor(census_tract)206 -3.144e+05  4.731e+04  -6.646 3.10e-11 ***\nas.factor(census_tract)207 -3.372e+05  3.997e+04  -8.437  < 2e-16 ***\nas.factor(census_tract)208 -3.241e+05  6.316e+04  -5.132 2.90e-07 ***\nas.factor(census_tract)209 -3.238e+05  4.248e+04  -7.624 2.58e-14 ***\nas.factor(census_tract)21  -3.321e+05  3.653e+04  -9.089  < 2e-16 ***\nas.factor(census_tract)210 -3.124e+05  4.298e+04  -7.268 3.78e-13 ***\nas.factor(census_tract)211 -3.130e+05  4.445e+04  -7.042 1.96e-12 ***\nas.factor(census_tract)212 -3.103e+05  4.505e+04  -6.887 5.87e-12 ***\nas.factor(census_tract)213 -3.027e+05  4.432e+04  -6.830 8.77e-12 ***\nas.factor(census_tract)214 -2.951e+05  4.410e+04  -6.692 2.26e-11 ***\nas.factor(census_tract)215 -3.198e+05  4.483e+04  -7.135 1.01e-12 ***\nas.factor(census_tract)216 -3.378e+05  4.865e+04  -6.943 3.96e-12 ***\nas.factor(census_tract)217 -3.140e+05  4.610e+04  -6.810 1.01e-11 ***\nas.factor(census_tract)218 -2.771e+05  5.342e+04  -5.187 2.16e-07 ***\nas.factor(census_tract)219 -2.661e+05  5.188e+04  -5.129 2.95e-07 ***\nas.factor(census_tract)22  -3.683e+05  3.732e+04  -9.869  < 2e-16 ***\nas.factor(census_tract)220 -3.480e+05  5.266e+04  -6.609 3.98e-11 ***\nas.factor(census_tract)23  -3.225e+05  3.754e+04  -8.592  < 2e-16 ***\nas.factor(census_tract)231 -6.475e+04  5.328e+04  -1.215 0.224234    \nas.factor(census_tract)235 -1.784e+05  4.906e+04  -3.636 0.000278 ***\nas.factor(census_tract)236 -2.624e+05  4.740e+04  -5.535 3.16e-08 ***\nas.factor(census_tract)237 -3.482e+05  4.648e+04  -7.492 7.12e-14 ***\nas.factor(census_tract)238 -3.699e+05  4.665e+04  -7.930 2.32e-15 ***\nas.factor(census_tract)24  -3.130e+05  3.569e+04  -8.770  < 2e-16 ***\nas.factor(census_tract)240 -3.892e+05  4.716e+04  -8.253  < 2e-16 ***\nas.factor(census_tract)241 -4.161e+05  5.317e+04  -7.825 5.36e-15 ***\nas.factor(census_tract)242 -4.392e+05  4.582e+04  -9.585  < 2e-16 ***\nas.factor(census_tract)243 -4.168e+05  4.442e+04  -9.383  < 2e-16 ***\nas.factor(census_tract)244 -4.885e+05  4.561e+04 -10.712  < 2e-16 ***\nas.factor(census_tract)245 -4.342e+05  4.641e+04  -9.356  < 2e-16 ***\nas.factor(census_tract)246 -4.170e+05  4.794e+04  -8.699  < 2e-16 ***\nas.factor(census_tract)247 -4.583e+05  4.642e+04  -9.872  < 2e-16 ***\nas.factor(census_tract)248 -4.093e+05  4.894e+04  -8.364  < 2e-16 ***\nas.factor(census_tract)249 -3.960e+05  4.823e+04  -8.211 2.34e-16 ***\nas.factor(census_tract)25  -3.129e+05  3.616e+04  -8.653  < 2e-16 ***\nas.factor(census_tract)252 -4.006e+05  4.726e+04  -8.477  < 2e-16 ***\nas.factor(census_tract)253 -3.692e+05  4.722e+04  -7.819 5.61e-15 ***\nas.factor(census_tract)254 -3.794e+05  4.814e+04  -7.881 3.42e-15 ***\nas.factor(census_tract)255 -2.859e+05  5.113e+04  -5.591 2.28e-08 ***\nas.factor(census_tract)256 -2.637e+05  4.892e+04  -5.391 7.11e-08 ***\nas.factor(census_tract)257 -1.107e+05  5.132e+04  -2.158 0.030946 *  \nas.factor(census_tract)258 -3.479e+05  5.377e+04  -6.469 1.01e-10 ***\nas.factor(census_tract)259 -3.710e+05  5.091e+04  -7.287 3.29e-13 ***\nas.factor(census_tract)260 -3.683e+05  5.158e+04  -7.140 9.67e-13 ***\nas.factor(census_tract)261 -3.628e+05  5.180e+04  -7.005 2.56e-12 ***\nas.factor(census_tract)262 -3.962e+05  4.880e+04  -8.120 4.96e-16 ***\nas.factor(census_tract)263 -3.916e+05  4.885e+04  -8.016 1.15e-15 ***\nas.factor(census_tract)264 -3.887e+05  4.846e+04  -8.022 1.10e-15 ***\nas.factor(census_tract)265 -3.879e+05  4.794e+04  -8.092 6.23e-16 ***\nas.factor(census_tract)266 -3.812e+05  4.879e+04  -7.812 5.93e-15 ***\nas.factor(census_tract)267 -4.035e+05  4.720e+04  -8.549  < 2e-16 ***\nas.factor(census_tract)268 -4.475e+05  5.206e+04  -8.595  < 2e-16 ***\nas.factor(census_tract)269 -4.419e+05  5.382e+04  -8.210 2.35e-16 ***\nas.factor(census_tract)27  -3.868e+05  3.552e+04 -10.889  < 2e-16 ***\nas.factor(census_tract)270 -4.765e+05  5.092e+04  -9.358  < 2e-16 ***\nas.factor(census_tract)271 -4.013e+05  4.900e+04  -8.188 2.83e-16 ***\nas.factor(census_tract)272 -3.929e+05  4.849e+04  -8.104 5.66e-16 ***\nas.factor(census_tract)273 -3.976e+05  4.688e+04  -8.481  < 2e-16 ***\nas.factor(census_tract)274 -4.180e+05  4.523e+04  -9.241  < 2e-16 ***\nas.factor(census_tract)275 -4.209e+05  4.631e+04  -9.090  < 2e-16 ***\nas.factor(census_tract)276 -3.927e+05  4.830e+04  -8.129 4.59e-16 ***\nas.factor(census_tract)277 -3.880e+05  4.737e+04  -8.190 2.78e-16 ***\nas.factor(census_tract)278 -4.139e+05  4.752e+04  -8.710  < 2e-16 ***\nas.factor(census_tract)279 -3.973e+05  4.579e+04  -8.675  < 2e-16 ***\nas.factor(census_tract)28  -3.362e+05  3.557e+04  -9.452  < 2e-16 ***\nas.factor(census_tract)280 -4.019e+05  4.453e+04  -9.025  < 2e-16 ***\nas.factor(census_tract)281 -4.671e+05  4.592e+04 -10.173  < 2e-16 ***\nas.factor(census_tract)282 -4.343e+05  4.684e+04  -9.271  < 2e-16 ***\nas.factor(census_tract)283 -4.613e+05  4.504e+04 -10.243  < 2e-16 ***\nas.factor(census_tract)284 -4.441e+05  4.483e+04  -9.906  < 2e-16 ***\nas.factor(census_tract)285 -4.498e+05  4.606e+04  -9.766  < 2e-16 ***\nas.factor(census_tract)286 -4.440e+05  4.393e+04 -10.107  < 2e-16 ***\nas.factor(census_tract)287 -4.466e+05  4.654e+04  -9.595  < 2e-16 ***\nas.factor(census_tract)288 -4.367e+05  4.496e+04  -9.714  < 2e-16 ***\nas.factor(census_tract)289 -4.255e+05  4.426e+04  -9.613  < 2e-16 ***\nas.factor(census_tract)29  -2.853e+05  3.594e+04  -7.938 2.17e-15 ***\nas.factor(census_tract)290 -4.202e+05  4.586e+04  -9.164  < 2e-16 ***\nas.factor(census_tract)291 -3.937e+05  4.692e+04  -8.391  < 2e-16 ***\nas.factor(census_tract)292 -4.307e+05  4.533e+04  -9.501  < 2e-16 ***\nas.factor(census_tract)293 -4.564e+05  4.538e+04 -10.058  < 2e-16 ***\nas.factor(census_tract)294 -4.372e+05  4.709e+04  -9.284  < 2e-16 ***\nas.factor(census_tract)298 -3.817e+05  4.693e+04  -8.133 4.44e-16 ***\nas.factor(census_tract)299 -3.936e+05  4.701e+04  -8.372  < 2e-16 ***\nas.factor(census_tract)3    8.834e+04  4.419e+04   1.999 0.045600 *  \nas.factor(census_tract)30  -4.165e+05  3.557e+04 -11.711  < 2e-16 ***\nas.factor(census_tract)300 -4.150e+05  4.625e+04  -8.973  < 2e-16 ***\nas.factor(census_tract)301 -4.369e+05  4.702e+04  -9.293  < 2e-16 ***\nas.factor(census_tract)302 -4.187e+05  4.619e+04  -9.065  < 2e-16 ***\nas.factor(census_tract)305 -3.931e+05  4.655e+04  -8.446  < 2e-16 ***\nas.factor(census_tract)306 -3.634e+05  4.793e+04  -7.581 3.61e-14 ***\nas.factor(census_tract)307 -3.536e+05  5.323e+04  -6.642 3.18e-11 ***\nas.factor(census_tract)308 -3.579e+05  4.917e+04  -7.279 3.51e-13 ***\nas.factor(census_tract)309 -3.643e+05  5.165e+04  -7.053 1.82e-12 ***\nas.factor(census_tract)31  -4.461e+05  3.556e+04 -12.543  < 2e-16 ***\nas.factor(census_tract)310 -3.625e+05  4.923e+04  -7.363 1.88e-13 ***\nas.factor(census_tract)311 -3.883e+05  4.724e+04  -8.219  < 2e-16 ***\nas.factor(census_tract)312 -3.782e+05  4.760e+04  -7.946 2.04e-15 ***\nas.factor(census_tract)313 -3.858e+05  4.794e+04  -8.048 8.94e-16 ***\nas.factor(census_tract)314 -3.601e+05  4.845e+04  -7.431 1.13e-13 ***\nas.factor(census_tract)315 -3.443e+05  4.900e+04  -7.027 2.19e-12 ***\nas.factor(census_tract)316 -3.386e+05  4.823e+04  -7.020 2.30e-12 ***\nas.factor(census_tract)317 -3.739e+05  4.807e+04  -7.779 7.68e-15 ***\nas.factor(census_tract)318 -3.733e+05  4.807e+04  -7.766 8.56e-15 ***\nas.factor(census_tract)319 -3.892e+05  4.740e+04  -8.211 2.33e-16 ***\nas.factor(census_tract)32  -4.610e+05  3.614e+04 -12.756  < 2e-16 ***\nas.factor(census_tract)320 -3.777e+05  4.774e+04  -7.912 2.68e-15 ***\nas.factor(census_tract)321 -3.984e+05  4.782e+04  -8.331  < 2e-16 ***\nas.factor(census_tract)323 -3.665e+05  4.869e+04  -7.527 5.43e-14 ***\nas.factor(census_tract)325 -3.718e+05  4.898e+04  -7.591 3.32e-14 ***\nas.factor(census_tract)326 -3.892e+05  4.907e+04  -7.931 2.29e-15 ***\nas.factor(census_tract)329 -3.629e+05  5.185e+04  -7.000 2.65e-12 ***\nas.factor(census_tract)33  -4.804e+05  3.627e+04 -13.244  < 2e-16 ***\nas.factor(census_tract)330 -3.820e+05  4.971e+04  -7.684 1.62e-14 ***\nas.factor(census_tract)331 -3.695e+05  5.001e+04  -7.389 1.54e-13 ***\nas.factor(census_tract)332 -3.087e+05  5.042e+04  -6.123 9.40e-10 ***\nas.factor(census_tract)333 -2.924e+05  5.208e+04  -5.614 2.01e-08 ***\nas.factor(census_tract)334 -3.179e+05  5.237e+04  -6.071 1.29e-09 ***\nas.factor(census_tract)335 -3.337e+05  5.195e+04  -6.424 1.36e-10 ***\nas.factor(census_tract)336 -3.101e+05  5.243e+04  -5.916 3.37e-09 ***\nas.factor(census_tract)337 -3.205e+05  5.175e+04  -6.194 5.98e-10 ***\nas.factor(census_tract)338 -3.330e+05  5.021e+04  -6.633 3.38e-11 ***\nas.factor(census_tract)339 -3.072e+05  5.192e+04  -5.917 3.33e-09 ***\nas.factor(census_tract)340 -3.326e+05  5.090e+04  -6.534 6.57e-11 ***\nas.factor(census_tract)341 -3.258e+05  5.161e+04  -6.312 2.82e-10 ***\nas.factor(census_tract)342 -3.423e+05  5.360e+04  -6.386 1.75e-10 ***\nas.factor(census_tract)344 -3.182e+05  5.446e+04  -5.842 5.25e-09 ***\nas.factor(census_tract)345 -3.037e+05  5.682e+04  -5.344 9.20e-08 ***\nas.factor(census_tract)346 -2.742e+05  7.176e+04  -3.821 0.000133 ***\nas.factor(census_tract)347 -3.262e+05  5.211e+04  -6.259 3.95e-10 ***\nas.factor(census_tract)348 -3.506e+05  5.420e+04  -6.470 1.01e-10 ***\nas.factor(census_tract)349 -3.572e+05  5.302e+04  -6.738 1.65e-11 ***\nas.factor(census_tract)351 -3.799e+05  6.386e+04  -5.949 2.75e-09 ***\nas.factor(census_tract)352 -3.466e+05  5.632e+04  -6.154 7.72e-10 ***\nas.factor(census_tract)353 -3.665e+05  5.803e+04  -6.317 2.74e-10 ***\nas.factor(census_tract)355 -3.162e+05  5.735e+04  -5.514 3.55e-08 ***\nas.factor(census_tract)356 -3.111e+05  5.726e+04  -5.433 5.61e-08 ***\nas.factor(census_tract)357 -3.562e+05  6.229e+04  -5.719 1.09e-08 ***\nas.factor(census_tract)358 -3.872e+05  6.419e+04  -6.032 1.65e-09 ***\nas.factor(census_tract)359 -3.365e+05  6.478e+04  -5.193 2.09e-07 ***\nas.factor(census_tract)36  -4.544e+05  3.861e+04 -11.768  < 2e-16 ***\nas.factor(census_tract)360 -3.141e+05  6.432e+04  -4.883 1.06e-06 ***\nas.factor(census_tract)361 -4.005e+05  6.475e+04  -6.185 6.33e-10 ***\nas.factor(census_tract)362 -3.828e+05  6.092e+04  -6.284 3.38e-10 ***\nas.factor(census_tract)363 -4.237e+05  6.580e+04  -6.440 1.22e-10 ***\nas.factor(census_tract)364 -4.976e+05  9.673e+04  -5.144 2.71e-07 ***\nas.factor(census_tract)365 -4.150e+05  6.840e+04  -6.067 1.33e-09 ***\nas.factor(census_tract)366 -3.608e+05  1.021e+05  -3.534 0.000411 ***\nas.factor(census_tract)367 -3.116e+05  3.825e+04  -8.148 3.94e-16 ***\nas.factor(census_tract)37  -4.455e+05  3.656e+04 -12.184  < 2e-16 ***\nas.factor(census_tract)372 -3.806e+05  3.858e+04  -9.865  < 2e-16 ***\nas.factor(census_tract)373 -2.994e+05  4.082e+04  -7.334 2.33e-13 ***\nas.factor(census_tract)375 -4.122e+05  4.530e+04  -9.099  < 2e-16 ***\nas.factor(census_tract)376 -3.585e+05  5.894e+04  -6.083 1.20e-09 ***\nas.factor(census_tract)377 -5.188e+05  4.472e+04 -11.602  < 2e-16 ***\nas.factor(census_tract)378 -3.694e+05  3.973e+04  -9.298  < 2e-16 ***\nas.factor(census_tract)379 -3.891e+05  4.071e+04  -9.557  < 2e-16 ***\nas.factor(census_tract)38  -3.656e+05  3.783e+04  -9.665  < 2e-16 ***\nas.factor(census_tract)380 -4.384e+05  4.560e+04  -9.614  < 2e-16 ***\nas.factor(census_tract)381 -3.617e+05  5.269e+04  -6.864 6.90e-12 ***\nas.factor(census_tract)382 -3.973e+05  4.246e+04  -9.357  < 2e-16 ***\nas.factor(census_tract)384 -3.062e+05  5.097e+04  -6.009 1.91e-09 ***\nas.factor(census_tract)385 -2.030e+04  5.183e+04  -0.392 0.695308    \nas.factor(census_tract)386 -6.941e+04  5.106e+04  -1.359 0.174075    \nas.factor(census_tract)387 -8.321e+03  5.286e+04  -0.157 0.874916    \nas.factor(census_tract)388 -2.345e+05  4.693e+04  -4.996 5.90e-07 ***\nas.factor(census_tract)389 -3.914e+05  4.914e+04  -7.965 1.75e-15 ***\nas.factor(census_tract)39  -3.856e+05  3.641e+04 -10.591  < 2e-16 ***\nas.factor(census_tract)390 -4.045e+05  4.601e+04  -8.791  < 2e-16 ***\nas.factor(census_tract)391 -4.680e+05  4.476e+04 -10.456  < 2e-16 ***\nas.factor(census_tract)40  -3.770e+05  3.627e+04 -10.394  < 2e-16 ***\nas.factor(census_tract)41  -4.278e+05  3.622e+04 -11.810  < 2e-16 ***\nas.factor(census_tract)42  -4.051e+05  3.630e+04 -11.160  < 2e-16 ***\nas.factor(census_tract)54  -4.323e+05  8.135e+04  -5.314 1.09e-07 ***\nas.factor(census_tract)55  -4.009e+05  4.436e+04  -9.037  < 2e-16 ***\nas.factor(census_tract)56  -4.096e+05  8.068e+04  -5.077 3.88e-07 ***\nas.factor(census_tract)60  -4.243e+05  4.306e+04  -9.853  < 2e-16 ***\nas.factor(census_tract)61  -4.386e+05  4.546e+04  -9.647  < 2e-16 ***\nas.factor(census_tract)62  -4.403e+05  4.232e+04 -10.404  < 2e-16 ***\nas.factor(census_tract)63  -4.503e+05  4.433e+04 -10.158  < 2e-16 ***\nas.factor(census_tract)64  -4.628e+05  4.283e+04 -10.806  < 2e-16 ***\nas.factor(census_tract)65  -4.375e+05  4.102e+04 -10.666  < 2e-16 ***\nas.factor(census_tract)66  -3.820e+05  4.338e+04  -8.805  < 2e-16 ***\nas.factor(census_tract)67  -4.592e+05  4.062e+04 -11.305  < 2e-16 ***\nas.factor(census_tract)7    7.915e+04  6.543e+04   1.210 0.226412    \nas.factor(census_tract)70  -4.776e+05  4.113e+04 -11.610  < 2e-16 ***\nas.factor(census_tract)71  -4.515e+05  4.042e+04 -11.169  < 2e-16 ***\nas.factor(census_tract)72  -4.689e+05  4.111e+04 -11.405  < 2e-16 ***\nas.factor(census_tract)73  -4.368e+05  4.039e+04 -10.814  < 2e-16 ***\nas.factor(census_tract)74  -4.598e+05  3.971e+04 -11.580  < 2e-16 ***\nas.factor(census_tract)77  -3.708e+05  4.394e+04  -8.438  < 2e-16 ***\nas.factor(census_tract)78  -2.976e+05  4.130e+04  -7.207 5.93e-13 ***\nas.factor(census_tract)79  -2.265e+05  3.953e+04  -5.730 1.02e-08 ***\nas.factor(census_tract)8   -3.981e+03  4.620e+04  -0.086 0.931335    \nas.factor(census_tract)80  -3.662e+05  4.004e+04  -9.145  < 2e-16 ***\nas.factor(census_tract)81  -4.458e+05  4.017e+04 -11.097  < 2e-16 ***\nas.factor(census_tract)82  -4.529e+05  4.209e+04 -10.761  < 2e-16 ***\nas.factor(census_tract)83  -4.304e+05  4.197e+04 -10.254  < 2e-16 ***\nas.factor(census_tract)84  -4.585e+05  4.240e+04 -10.814  < 2e-16 ***\nas.factor(census_tract)85  -4.222e+05  4.037e+04 -10.460  < 2e-16 ***\nas.factor(census_tract)86  -3.388e+05  4.166e+04  -8.132 4.50e-16 ***\nas.factor(census_tract)87  -1.977e+05  4.120e+04  -4.800 1.60e-06 ***\nas.factor(census_tract)88  -2.321e+05  7.748e+04  -2.996 0.002738 ** \nas.factor(census_tract)9   -9.576e+04  4.708e+04  -2.034 0.041938 *  \nas.factor(census_tract)90  -3.003e+05  5.077e+04  -5.914 3.40e-09 ***\nas.factor(census_tract)91  -4.070e+05  4.985e+04  -8.165 3.42e-16 ***\nas.factor(census_tract)92  -4.138e+05  4.187e+04  -9.882  < 2e-16 ***\nas.factor(census_tract)93  -4.928e+05  4.148e+04 -11.879  < 2e-16 ***\nas.factor(census_tract)94  -4.474e+05  4.258e+04 -10.507  < 2e-16 ***\nas.factor(census_tract)95  -4.563e+05  4.323e+04 -10.554  < 2e-16 ***\nas.factor(census_tract)96  -4.484e+05  4.246e+04 -10.561  < 2e-16 ***\nas.factor(census_tract)98  -4.173e+05  4.408e+04  -9.466  < 2e-16 ***\ndist_septa:pct_no_vehicle  -9.685e+01  6.939e+01  -1.396 0.162791    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 95860 on 18154 degrees of freedom\nMultiple R-squared:  0.783,\tAdjusted R-squared:  0.7791 \nF-statistic: 198.5 on 330 and 18154 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nFor the fifth and final model, the fourth specification was further extended by adding census tract fixed effects through as.factor(census_tract). This final model retains all previously included structural, spatial, socioeconomic, non-linear, and interaction terms, while also controlling for unobserved tract-level characteristics that may systematically influence housing prices. By including a separate fixed effect for each census tract, the model accounts for localized neighborhood factors that are not directly measured by the other variables, such as tract-specific housing market conditions, built environment context, or other place-based influences. This final specification was intended to capture both property-level variation and broader neighborhood-level differences more completely. Among all five models, Model 5 produced the highest R².\n\n## Diagnostic plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#10-fold CV\nset.seed(123)\n\ntrain_control <- trainControl(\n  method = \"cv\",\n  number = 10\n)\n\ncv_m1 <- train(\n  sale_price ~ total_livable_area + number_of_bedrooms + number_of_bathrooms + garage_spaces + fireplaces + interior_condition + age + I(age^2),\n  data = model_df, method = \"lm\", trControl = train_control\n)\n\ncv_m2 <- train(\n  sale_price ~ total_livable_area + number_of_bedrooms + number_of_bathrooms + garage_spaces + fireplaces + interior_condition + age + I(age^2) + crime_400m + knn_school_dist + knn_park_dist + dist_septa + vacant_300m + median_income + pct_no_vehicle,\n  data = model_df, method = \"lm\", trControl = train_control\n)\n\ncv_m3 <- train(\n  sale_price ~ total_livable_area + number_of_bedrooms + number_of_bathrooms + garage_spaces + fireplaces + interior_condition + age + I(age^2) + crime_400m + knn_school_dist + knn_park_dist + dist_septa + vacant_300m + median_income + pct_no_vehicle + dist_center + dist_center_sq ,\n  data = model_df, method = \"lm\", trControl = train_control\n)\n\ncv_m4 <- train(\n  sale_price ~ total_livable_area + number_of_bedrooms + number_of_bathrooms + garage_spaces + fireplaces + interior_condition + age + I(age^2) + crime_400m + knn_school_dist + knn_park_dist + dist_septa + vacant_300m + median_income + pct_no_vehicle + dist_center + dist_center_sq + dist_septa * pct_no_vehicle,\n  data = model_df, method = \"lm\", trControl = train_control\n)\n\ncv_m5 <- train(\n  sale_price ~ total_livable_area + number_of_bedrooms + number_of_bathrooms + garage_spaces + fireplaces + interior_condition + age + I(age^2) + crime_400m + knn_school_dist + knn_park_dist + dist_septa + vacant_300m + median_income + pct_no_vehicle + dist_center + dist_center_sq + dist_septa * pct_no_vehicle + as.factor(census_tract),\n  data = model_df, method = \"lm\", trControl = train_control\n)\n\nmodel_compare <- data.frame(\n  Model = c(\n    \"Structural\",\n    \"Spatial + Socioeconomic\",\n    \"Non-linear term\",\n    \"Interaction\",\n    \"Fixed Effect\"\n  ),\n  Rsquared = c(\n    cv_m1$results$Rsquared,\n    cv_m2$results$Rsquared,\n    cv_m3$results$Rsquared,\n    cv_m4$results$Rsquared,\n    cv_m5$results$Rsquared\n  ),\n  RMSE = c(\n    cv_m1$results$RMSE,\n    cv_m2$results$RMSE,\n    cv_m3$results$RMSE,\n    cv_m4$results$RMSE,\n    cv_m5$results$RMSE\n  ),\n  MAE = c(\n    cv_m1$results$MAE,\n    cv_m2$results$MAE,\n    cv_m3$results$MAE,\n    cv_m4$results$MAE,\n    cv_m5$results$MAE\n  )\n) |>\n  mutate(\n    R2 = round(Rsquared, 3),\n    RMSE = round(RMSE, 0),\n    MAE = round(MAE, 0)\n  ) |>\n  select(\n    Model,\n    `R² (CV)` = R2,\n    `RMSE (CV)` = RMSE,\n    `MAE (CV)` = MAE\n  )\n\nmodel_compare\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    Model R² (CV) RMSE (CV) MAE (CV)\n1              Structural   0.555    135959    92434\n2 Spatial + Socioeconomic   0.688    113903    70801\n3         Non-linear term   0.703    111192    68744\n4             Interaction   0.703    111147    68775\n5            Fixed Effect   0.771     97490    57270\n```\n\n\n:::\n:::\n\n\nThe 10-fold cross-validation results show that the Fixed Effect model performed best among all five specifications. It achieved the highest cross-validated R² (0.771), meaning it explained about 77.1% of the variation in sale prices in out-of-sample prediction. It also produced the lowest RMSE (97,498) and the lowest MAE (57,277), indicating that its prediction errors were smaller on average than those of the other models. Compared with the earlier models, predictive performance improved steadily as additional complexity was introduced, with especially noticeable gains after adding spatial and socioeconomic variables and then neighborhood fixed effects. Although the non-linear and interaction models slightly improved performance over the simpler specifications, the Fixed Effect model provided the strongest overall generalization, suggesting that neighborhood-level differences play an important role in explaining housing prices. For that reason, the fifth model with Fixed Effect was selected as the final model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Residual Plot\nmodel_df$residuals <- residuals(m5)\nmodel_df$fitted <- fitted(m5)\n\nggplot(model_df, aes(x = fitted, y = residuals)) +\n  geom_point(alpha = 0.4, size = 1.2) +\n  geom_hline(yintercept = 0, color = \"red\", linetype = \"dashed\") +\n  labs(\n    title = \"Residual Plot\",\n    x = \"Fitted Values\",\n    y = \"Residuals\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe residuals are generally centered around zero and appear to be fairly randomly scattered, without a clear curved pattern. This suggests that the model is not missing a major systematic relationship.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Breusch-Pagan Test for Heteroskedasticity\n\nbp_test <- bptest(m5)\nbp_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  m5\nBP = 1187.1, df = 330, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\nThe Breusch–Pagan test indicates strong evidence of heteroskedasticity in the final model, meaning the variance of the residuals is not constant across fitted values. This pattern is also visible in the residual plot, where the spread of residuals changes over the range of predicted sale prices and becomes less stable for higher-value properties. Even so, the fixed effect model remains the preferred specification for prediction because it performed best in cross-validation. However, to make statistical inference more reliable, the model should be reported with standard errors adjusted for heteroskedasticity.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Q-Q Plot for Normality of Residuals\n\n\nqq_df <- data.frame(residuals = residuals(m5))\n\nggplot(qq_df, aes(sample = residuals)) +\n  stat_qq(alpha = 0.5) +\n  stat_qq_line(color = \"red\", linewidth = 1) +\n  labs(\n    title = \"Q-Q Plot of Residuals\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\nThe Q-Q plot shows substantial deviation from the reference line, especially in the upper tail, indicating that the residuals are not normally distributed. While observations near the center of the distribution lie relatively close to the reference line, both tails diverge noticeably, with the upper tail showing especially strong upward curvature. This suggests that the residual distribution is right-skewed and contains substantial outliers, particularly among observations with large positive residuals. In practical terms, the model fits the bulk of observations more closely than the extreme cases, where underprediction appears to be more pronounced.\n\n::: {.cell}\n\n```{.r .cell-code}\n#Cook's Distance\n\n# Add diagnostic measures to tibble\ndiagnostic_data <- augment(m5, data = model_df) |>\n  mutate(\n    cooks_d = .cooksd,\n    leverage = .hat,\n    is_influential = cooks_d > 4 / nrow(model_df)\n  )\n\n# Plot Cook's Distance\nggplot(diagnostic_data, aes(x = 1:nrow(diagnostic_data), y = cooks_d)) +\n  geom_point(aes(color = is_influential), size = 2) +\n  geom_hline(\n    yintercept = 4 / nrow(diagnostic_data),\n    linetype = \"dashed\",\n    color = \"red\"\n  ) +\n  scale_color_manual(values = c(\"grey60\", \"red\")) +\n  labs(\n    title = \"Cook's Distance\",\n    x = \"Observation\",\n    y = \"Cook's D\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nMost observations have very small Cook’s Distance values, suggesting that they do not strongly influence the fitted model. However, a small number of points stand out with noticeably higher Cook’s D values, indicating that a few observations may have a relatively strong influence on the regression results.\n\n## Conclusion & Interpretations\n\nFinal model’s accuracy:\nModel 5 is the final and preferred model for prediction because it performs best among all five specifications. Its stronger performance suggests that location and tract-level differences are highly important in explaining variation in residential sale prices. At the same time, the diagnostic results indicate the presence of heteroskedasticity, non-normal residuals, and a small number of influential observations. As a result, while Model 5 provides the strongest overall predictive accuracy, its coefficient estimates should be interpreted carefully.\n\nWhich features matter most for Philadelphia prices:\nNeighborhood and census tract effects appear to matter most for Philadelphia housing prices, as model performance improved substantially after tract-level fixed effects were added. This suggests that local context plays a major role in shaping sale prices beyond the structural features of individual homes. In other words, where a property is located is highly influential, and tract-level differences capture important neighborhood conditions that are not fully explained by the other variables in the model.\n\nHardest neighborhood to predict:\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n# 1 Add Model 5 residuals back to model_df\n\nmodel_resid <- model_df %>%\n  mutate(resid = resid(m5))\n\n#2\ntract_resid1 <- model_resid %>%\n  group_by(census_tract) %>%   # <-- my tract column in model_df\n  summarise(mean_resid = mean(resid, na.rm = TRUE))\n\n#2.5 standardlize the mean residual\ntract_resid1 <- tract_resid1 %>%\n  mutate(sd_mean_resid = scale(mean_resid))\n\n#3 Join to tract_sf\ntract_sf_resid <- tracts_sf %>%\n  left_join(tract_resid1, by = c(\"NAME10\" = \"census_tract\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# choose number of classes\nn_class <- 7\n\n# make Jenks / natural breaks\nbrks <- classIntervals(\n  tract_sf_resid$sd_mean_resid,\n  n = n_class,\n  style = \"jenks\"\n)$brks\n\n# create pretty labels\nlabs_q <- paste0(\n  round(head(brks, -1), 2),\n  \" to \",\n  round(tail(brks, -1), 2)\n)\n\n# cut into classes\ntract_sf_resid <- tract_sf_resid %>%\n  mutate(\n    q_resid = cut(\n      sd_mean_resid,\n      breaks = brks,\n      include.lowest = TRUE,\n      labels = labs_q\n    )\n  )\n\n# filter highlighted tract\ntract1 <- tract_sf_resid %>%\n  filter(NAME10 == \"1\")\n\n# map\nggplot(tract_sf_resid) +\n  geom_sf(aes(fill = q_resid), color = \"grey75\", linewidth = 0.2) +\n  geom_sf(data = tract1, fill = NA, color = \"yellow\", linewidth = 0.8) +\n  scale_fill_brewer(\n    palette = \"RdBu\",\n    direction = -1,\n    na.value = \"grey85\",\n    name = \"Std. mean residual\"\n  ) +\n  labs(\n    title = \"Mean Residuals by Census Tract\",\n    subtitle = \"Blue tracts indicate underprediction; red tracts indicate overprediction\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\nCensus Tract 1 (highlighted in yellow) appears to be the hardest neighborhood to predict, as it has the largest residual in the final model. This indicates that sale prices in this tract are not being captured as accurately as in other parts of the city, suggesting that important local factors may still be missing from the model. Philadelphia Census Tract 1 is located in the Old City/Society Hill area. Its large residual may reflect unique neighborhood characteristics, historic housing stock, or localized market dynamics that are not fully explained by the included variables.\n\nEquity concerns:\nOne key equity concern is that a housing value model may reproduce existing neighborhood inequality rather than measure value in a neutral way. In Philadelphia, sale prices are shaped not only by housing characteristics, but also by long histories of segregation, disinvestment, and uneven public investment. As a result, the model may learn and reinforce patterns that already disadvantage certain neighborhoods. Another concern is that prediction errors may not be evenly distributed across space. If the model performs worse in some neighborhoods than others, those areas may be treated less fairly in assessment or policy decisions. In addition, some variables may act as indirect proxies for race, class, or neighborhood disadvantage, even if those characteristics are not directly included. This means a model can be statistically accurate overall while still raising important fairness concerns.\n\n\nLimitations:\nThis analysis has several important limitations. First, the model was estimated using observed sale prices, which reflect not only housing characteristics and location, but also broader market conditions and long-standing structural inequalities. As a result, the model predicts how the market values properties, not necessarily their intrinsic or socially fair value. Second, some extreme sale price outliers were removed to improve model stability and predictive accuracy. While this helps reduce the influence of unusual observations, it also means the model may be less able to represent the full range of the housing market, especially very high-value or highly atypical properties. In other words, trimming outliers improves performance for the majority of observations but may reduce accuracy at the extremes. A further limitation is that the model may still omit important variables that influence housing values, such as detailed housing renovations, school perception, or block-level amenities that are difficult to measure. In addition, the diagnostic results show evidence of heteroskedasticity, non-normal residuals, and a small number of influential observations. This suggests that model errors are not perfectly well behaved, and coefficient estimates should therefore be interpreted with caution. Finally, although census tract fixed effects improved the model’s predictive accuracy, they mainly capture neighborhood differences rather than explain exactly what causes them. This improves model fit, but it also makes the results harder to interpret and may hide deeper structural inequalities across neighborhoods. In the future,the findings would benefit from further examination using additional variables, alternative model forms, and more detailed neighborhood-level analysis.\n\n\n\n\nPortions of the written text in this report were assisted by ChatGPT for grammatical correction, stylistic refinement, and clarity of expression. ChatGPT was also used to help identify coding errors and improve code readability. All analytical decisions, model construction, statistical interpretation, and final conclusions were determined and approved by the author.\n",
    "supporting": [
      "lab3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}