{
  "hash": "4d45b96463b5b2bea384c82eb9293a40",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: Veronica Zheng\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#data, number of things, crs\ntibble(\n  data = c(\"Hospitals\", \"Census tracts\", \"PA counties\"),\n  number = c(nrow(hospitals), nrow(census_tracts), nrow(pa_counties)),\n  epsg = c(st_crs(hospitals)$epsg, st_crs(census_tracts)$epsg, st_crs(pa_counties)$epsg),\n  crs = c(st_crs(hospitals)$Name, st_crs(census_tracts)$Name, st_crs(pa_counties)$Name)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|data          | number| epsg|crs                      |\n|:-------------|------:|----:|:------------------------|\n|Hospitals     |    223| 4326|WGS 84                   |\n|Census tracts |   3445| 4269|NAD83                    |\n|PA counties   |     67| 3857|WGS 84 / Pseudo-Mercator |\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n\nThere are 223 hospitals\n\n- How many census tracts?\n\nThere are 3445 tracts\n\n- What coordinate reference system is each dataset in?\n\nHospitals: 4326\tWGS 84\n\nCensus tracts: 4269\tNAD83\n\nPA counties: 3857\tWGS 84 / Pseudo-Mercator\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\nvars <- c(\n  pop_total = \"B01001_001\",\n  med_hhinc = \"B19013_001\",\n  m_65_66   = \"B01001_020\",\n  m_67_69   = \"B01001_021\",\n  m_70_74   = \"B01001_022\",\n  m_75_79   = \"B01001_023\",\n  m_80_84   = \"B01001_024\",\n  m_85_up   = \"B01001_025\",\n  f_65_66   = \"B01001_044\",\n  f_67_69   = \"B01001_045\",\n  f_70_74   = \"B01001_046\",\n  f_75_79   = \"B01001_047\",\n  f_80_84   = \"B01001_048\",\n  f_85_up   = \"B01001_049\"\n)\n\nPAdemographic <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = vars,\n  year = 2022,\n  survey = \"acs5\",\n  geometry = FALSE,\n  output = \"wide\"\n) |>\n  transmute(\n    GEOID,\n    pop_total = pop_totalE,\n    med_hhinc = med_hhincE,\n    pop_65plus = m_65_66E + m_67_69E + m_70_74E + m_75_79E + m_80_84E + m_85_upE + f_65_66E + f_67_69E + f_70_74E + f_75_79E + f_80_84E + f_85_upE\n  )\n\n# Join to tract boundaries\ntracts_demo <- census_tracts |>\n  left_join(PAdemographic, by = \"GEOID\")\n```\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n\n2022\n\n- How many tracts have missing income data?\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_med_hhinc = sum(is.na(tracts_demo$med_hhinc))\nprint(missing_med_hhinc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 62\n```\n\n\n:::\n:::\n\n62 have missing income data\n\n- What is the median income across all PA census tracts?\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian_income <- median(tracts_demo$med_hhinc, na.rm = TRUE)\nprint(paste0(\"$\", median_income))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"$70188\"\n```\n\n\n:::\n:::\n\nThe median income is $70188.\n\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n\n1. Low median household income (choose an appropriate threshold)\n\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\ntracts_demo <- tracts_demo |>\n  mutate(pct_65plus = pop_65plus / pop_total)\n\nlow_med_hhinc<- quantile(tracts_demo$med_hhinc, 0.25, na.rm = TRUE)\nsig_elderly_pop<- quantile(tracts_demo$pct_65plus, 0.75, na.rm = TRUE)\n\nvulnerable_tracts<-tracts_demo|>\n  filter(\n    !is.na(med_hhinc),\n    med_hhinc <= low_med_hhinc,\n    pct_65plus >= sig_elderly_pop\n  )\n```\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n\nI use the bottom 25% of PA tracts' median household income to filter the relatively low income tracts because this is comparable across the state and easy to interpret.\n\n- What elderly population threshold did you choose and why?\n\nI use the top 25% for the 65+ population share. This is because it is easy to interpret and also comparable across the state. Tracts with higher concentration of elderly are more likelyto face mobility and healthcare challenges.\n\n- How many tracts meet your vulnerability criteria?\n\n::: {.cell}\n\n```{.r .cell-code}\nvulnerable_tracts_num<-nrow(vulnerable_tracts)\nprint(vulnerable_tracts_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 165\n```\n\n\n:::\n:::\n\nThere are 165 tracts meet my criteria.\n\n- What percentage of PA census tracts are considered vulnerable by your definition?\n\n::: {.cell}\n\n```{.r .cell-code}\nvulnerable_tracts_pct<-vulnerable_tracts_num/nrow(census_tracts)* 100\nprint(paste0(round(vulnerable_tracts_pct, 1), \"%\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"4.8%\"\n```\n\n\n:::\n:::\n\nThere are 4.8% tracts are considered vulnerable.\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nvulnerable_tracts <- st_transform(vulnerable_tracts, 2272)\nhospitals <- st_transform(hospitals, 2272)\n\n# Calculate distance from each tract centroid to nearest hospital\ntract_pts <- st_centroid(vulnerable_tracts)\nnearest_idx <- st_nearest_feature(tract_pts, hospitals)\ndist_ft <- st_distance(tract_pts, hospitals[nearest_idx, ], by_element = TRUE)\n\nvulnerable_tracts$dist_to_hosp_miles <- as.numeric(dist_ft) / 5280\n```\n:::\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\nI choose NAD83 / Pennsylvania South (ftUS), which is the Pennsylvania State Plane coordinate system. It is accurate for distance measurements n Pennsylvania.\n\n**Questions to answer:**\n\n::: {.cell}\n\n```{.r .cell-code}\navg_dist <- mean(vulnerable_tracts$dist_to_hosp_miles, na.rm = TRUE)\nmax_dist <- max(vulnerable_tracts$dist_to_hosp_miles, na.rm = TRUE)\nn_over_15 <- sum(vulnerable_tracts$dist_to_hosp_miles > 15, na.rm = TRUE)\nprint(avg_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.745881\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(max_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.15872\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(n_over_15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n:::\n\n- What is the average distance to the nearest hospital for vulnerable tracts?\n\nThe average distance to nearest hospital is 4.75 miles.\n\n- What is the maximum distance?\n\nThe maximum distance to nearest hospital is 19.16 miles\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n\nThere are 9 tracts are more than 15 miles from the nearest hospital.\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\nvulnerable_tracts$underserved <- vulnerable_tracts$dist_to_hosp_miles > 15\n\ntracts_demo$vulnerable <- tracts_demo$GEOID %in% vulnerable_tracts$GEOID\n\n\ntracts_demo <- tracts_demo |>\n  left_join(\n    vulnerable_tracts |>\n      st_drop_geometry() |>\n      select(GEOID, dist_to_hosp_miles, underserved),\n    by = \"GEOID\"\n  ) |>\n  mutate(\n    underserved = ifelse(is.na(underserved), FALSE, underserved)\n  )\n```\n:::\n\n\n**Questions to answer:**\n\n::: {.cell}\n\n```{.r .cell-code}\nunderserved_tracts <- vulnerable_tracts[vulnerable_tracts$underserved, ]\nprint(nrow(underserved_tracts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(nrow(underserved_tracts)/nrow(vulnerable_tracts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05454545\n```\n\n\n:::\n:::\n\n- How many tracts are underserved?\n\nThere are 9 tracts are underserved.\n\n- What percentage of vulnerable tracts are underserved?\n\nThere are 5.45% of tracts are underserved.\n\n- Does this surprise you? Why or why not?\n\nIt does not surprise me because we have a lot of criteria to define underserved tracts. We have bottom 25% median income+ top 25% elderly as vulnerable tracts, and a spatial criteria of distance >15 miles. Also, we used the euclidean distance to the nearest hospital which will underestimate the real distance. If we switch the distance to road network, the underserved tract may be more.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\npa_counties <- st_transform(pa_counties, 2272)\ntracts_demo  <- st_transform(tracts_demo, 2272)\n\n# 1) Spatial join tracts to counties using a point per tract (avoids duplicates)\ntract_pts <- st_point_on_surface(tracts_demo)\ntracts_with_county <- st_join(tract_pts, pa_counties, join = st_within)\n\n# 2) Aggregate statistics by county\ncounty_stats <- tracts_with_county |>\n  st_drop_geometry() |>\n  group_by(COUNTY_NAM) |>\n  summarise(\n    n_vulnerable = sum(vulnerable, na.rm = TRUE),\n    n_underserved = sum(underserved, na.rm = TRUE),\n    pct_vuln_underserved = ifelse(n_vulnerable == 0, NA, 100 * n_underserved / n_vulnerable),\n    avg_dist_miles_vulnerable = mean(dist_to_hosp_miles[vulnerable], na.rm = TRUE),\n    total_vulnerable_pop = sum(pop_total[vulnerable], na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  arrange(desc(pct_vuln_underserved))\n```\n:::\n\n\n\n**Questions to answer:**\n\n::: {.cell}\n\n```{.r .cell-code}\ntop5 <- county_stats |>\n  filter(!is.na(COUNTY_NAM), n_vulnerable > 0) |>\n  arrange(desc(pct_vuln_underserved)) |>\n  slice(1:5)\n\nprint(top5$COUNTY_NAM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"BRADFORD\" \"FOREST\"   \"JUNIATA\"  \"MONROE\"   \"SULLIVAN\"\n```\n\n\n:::\n\n```{.r .cell-code}\ncounty_far_pop <- tracts_with_county |>\n  st_drop_geometry() |>\n  filter(!is.na(COUNTY_NAM)) |>\n  group_by(COUNTY_NAM) |>\n  summarise(far_vuln_pop = sum(pop_total[underserved], na.rm = TRUE), .groups = \"drop\") |>\n  arrange(desc(far_vuln_pop))\n\ntop_far <- county_far_pop |> slice(1:5)\nprint(top_far$COUNTY_NAM)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"BRADFORD\"   \"DAUPHIN\"    \"CLEARFIELD\" \"FOREST\"     \"CRAWFORD\"  \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(top_far$far_vuln_pop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5466 4018 3343 2701 2536\n```\n\n\n:::\n:::\n\n\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\n\n\"BRADFORD\" \"FOREST\"   \"JUNIATA\"  \"MONROE\"  and \"SULLIVAN\" have the highest percentage of underserved vulnerable tracts\n\n- Which counties have the most vulnerable people living far from hospitals?\n\n\"BRADFORD\"   \"DAUPHIN\"    \"CLEARFIELD\" \"FOREST\"  and  \"CRAWFORD\" have the most vulnerable people living far from hospitals from 5466 to 2536 people.\n\n- Are there any patterns in where underserved counties are located?\n\nThe underserved counties are mostly rural or small-town counties where ospitals are more sparsely distributed so the travel distances can be longer. Especially  Bradford, which has both the highest percentage of underserved vulnerable tracts and population, is located in northern Pennsylvania near the New York border.\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority \n\n  My priority metric is vulnerable population living > 15mlies, and the second metric is the vulnerable population share (since I only have 9 tracts of underserve tracts, in order to have a list of 10 counties, I add the second metric).\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# county total population (all tracts)\ncounty_total_pop <- tracts_with_county |>\n  st_drop_geometry() |>\n  filter(!is.na(COUNTY_NAM)) |>\n  group_by(COUNTY_NAM) |>\n  summarise(total_pop = sum(pop_total, na.rm = TRUE), .groups = \"drop\")\n\npriority_counties <- county_stats |>\n  filter(!is.na(COUNTY_NAM), n_vulnerable > 0) |>\n  left_join(county_far_pop, by = \"COUNTY_NAM\") |>\n  left_join(county_total_pop, by = \"COUNTY_NAM\") |>\n  mutate(\n    far_vuln_pop = ifelse(is.na(far_vuln_pop), 0, far_vuln_pop),\n    vuln_pop_share = total_vulnerable_pop / total_pop\n  ) |>\n  arrange(\n    desc(far_vuln_pop),     # Priority 1\n    desc(vuln_pop_share)    # Priority 2 (tie-breaker)\n  ) |>\n  slice(1:10) |>\n  transmute(\n    County = COUNTY_NAM,\n    `Vulnerable population >15 miles (priority 1)` = scales::comma(far_vuln_pop),\n    `Vulnerable population share (priority 2)` = scales::percent(vuln_pop_share, accuracy = 0.1),\n    `Vulnerable tracts (count)` = n_vulnerable,\n    `Underserved tracts (count)` = n_underserved,\n    `Underserved share of vulnerable tracts` = scales::percent(pct_vuln_underserved/100, accuracy = 0.1),\n    `Avg distance to hospital (vulnerable tracts, miles)` = round(avg_dist_miles_vulnerable, 2)\n  )\n\nknitr::kable(\n  priority_counties,\n  caption = \"Top 10 priority counties\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 priority counties\n\n|County     |Vulnerable population >15 miles (priority 1) |Vulnerable population share (priority 2) | Vulnerable tracts (count)| Underserved tracts (count)|Underserved share of vulnerable tracts | Avg distance to hospital (vulnerable tracts, miles)|\n|:----------|:--------------------------------------------|:----------------------------------------|-------------------------:|--------------------------:|:--------------------------------------|---------------------------------------------------:|\n|BRADFORD   |5,466                                        |9.1%                                     |                         1|                          1|100.0%                                 |                                               16.66|\n|DAUPHIN    |4,018                                        |2.9%                                     |                         2|                          1|50.0%                                  |                                                9.95|\n|CLEARFIELD |3,343                                        |16.4%                                    |                         4|                          1|25.0%                                  |                                               11.37|\n|FOREST     |2,701                                        |38.8%                                    |                         1|                          1|100.0%                                 |                                               18.13|\n|CRAWFORD   |2,536                                        |10.8%                                    |                         4|                          1|25.0%                                  |                                                8.35|\n|POTTER     |1,948                                        |55.3%                                    |                         3|                          1|33.3%                                  |                                                9.55|\n|JUNIATA    |1,782                                        |7.6%                                     |                         1|                          1|100.0%                                 |                                               15.91|\n|MONROE     |1,299                                        |0.8%                                     |                         1|                          1|100.0%                                 |                                               17.68|\n|SULLIVAN   |918                                          |15.6%                                    |                         1|                          1|100.0%                                 |                                               16.91|\n|UNION      |0                                            |22.8%                                    |                         2|                          0|0.0%                                   |                                                2.59|\n\n\n:::\n:::\n\n\n\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\npa_counties_map <- pa_counties |>\n  left_join(county_stats, by = \"COUNTY_NAM\")\n\nggplot() +\n  geom_sf(\n    data = pa_counties_map,\n    aes(fill = pct_vuln_underserved),\n    color = \"white\",\n    linewidth = 0.2\n  ) +\n  geom_sf(\n    data = hospitals,   # assumes hospitals is already EPSG:2272\n    color = \"red\",\n    size = 0.8,\n    alpha = 0.6\n  ) +\n  scale_fill_viridis_c(\n    option = \"C\",\n    na.value = \"grey90\",\n    labels = function(x) paste0(round(x, 0), \"%\"),\n    name = \"Underserved\\nshare (%)\"\n  ) +\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Counties shaded by % of vulnerable tracts that are underserved (>15 miles from nearest hospital)\",\n    caption = \"Source: ACS 2022 (5-year) via tidycensus; County boundaries + tracts via tigris; Hospitals from lecture dataset.\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption = element_text(size = 8)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nunderserved_tracts <- vulnerable_tracts |> filter(underserved)\n\n\nggplot() +\n  geom_sf(\n    data = tracts_demo,\n    fill = \"grey92\",\n    color = NA\n  ) +\n  # County boundaries for context\n  geom_sf(\n    data = pa_counties,\n    fill = NA,\n    color = \"white\",\n    linewidth = 0.3\n  ) +\n  # Underserved vulnerable tracts\n  geom_sf(\n    data = underserved_tracts,\n    fill = \"red\",\n    color = \"white\",\n    linewidth = 0.2\n  ) +\n  # Hospitals on top\n  geom_sf(\n    data = hospitals,\n    color = \"black\",\n    size = 0.8,\n    alpha = 0.7\n  ) +\n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania\",\n    subtitle = \"Highlighted vulnerable tracts >15 miles from the nearest hospital\",\n    caption = \"Source: ACS 2022 (5-year) via tidycensus; County boundaries + tracts via tigris; Hospitals from lecture dataset.\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption = element_text(size = 8),\n    legend.position = \"none\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nggplot(vulnerable_tracts, aes(x = dist_to_hosp_miles)) +\n  geom_histogram(bins = 30) +\n  geom_vline(xintercept = 15, linetype = \"dashed\") +\n  labs(\n    title = \"Distribution of Distance to the Nearest Hospital (Vulnerable Tracts)\",\n    subtitle = \"Dashed line indicates the underserved threshold (15 miles)\",\n    x = \"Distance to nearest hospital (miles)\",\n    y = \"Number of vulnerable census tracts\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n\nI chose the HIFLD Open Fire and Emergency Medical Service (EMS) Stations dataset because it provides statewide point locations of emergency service facilities.\n\n- What is the data source and date?\n\nThe data source is HIFLD Open (Homeland Infrastructure Foundation-Level Data) Fire and EMS Stations. The last modified dats is 10/24/2025.\n\n- How many features does it contain?\n\nIt contains 52057 points total, and points within PA is 2592.\n\n- What CRS is it in? Did you need to transform it?\n\nThe crs is 4326 WGS 84. I transform that to 2272.\n\n---\n\n2. **Pose a research question**\n\nAre vulnerable populations in Pennsylvania adequately covered by EMS stations within 2-mile response distance?\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1) Buffer EMS stations: 2 miles = 2*5280 ft\nems_bufs <- st_buffer(stations_pa, dist = 2 * 5280)\n\n# 2) Centroid for each vulnerable tract\nvuln_pts <- suppressWarnings(st_centroid(vulnerable_tracts))\n\n# 3) Coverage: point intersects ANY buffer (fast)\nhit_list <- st_intersects(vuln_pts, ems_bufs)   # sparse list\nvulnerable_tracts$ems_covered <- lengths(hit_list) > 0\n\n# Summary counts\nprint(paste(\"Vulnerable tracts covered (<=2 miles):\", sum(vulnerable_tracts$ems_covered)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Vulnerable tracts covered (<=2 miles): 140\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"Vulnerable tracts NOT covered:\", sum(!vulnerable_tracts$ems_covered)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Vulnerable tracts NOT covered: 25\"\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvuln_not_covered <- vulnerable_tracts |> filter(!ems_covered)\n\nggplot() +\n  geom_sf(data = pa_counties, fill = \"grey95\", color = \"white\", linewidth = 0.2) +\n  geom_sf(data = ems_bufs, fill = NA, color = \"blue\", linewidth = 0.2) +\n  geom_sf(data = vuln_not_covered, fill = \"red\", color = \"white\", linewidth = 0.2) +\n  geom_sf(data = stations_pa, color = \"black\", size = 0.3, alpha = 0.6) +\n  labs(\n    title = \"EMS Coverage for Vulnerable Tracts (2-mile Buffer)\",\n    subtitle = \"Red tracts: vulnerable centroids NOT inside any EMS station buffer\",\n    caption = \"2 miles is straight-line buffer distance (not driving time).\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/final map-1.png){width=672}\n:::\n:::\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\nUsing a 2-mile buffer around EMS stations, 140 of 165 vulnerable tracts are covered, and 25 are not covered. On the map, the not covered red trats are mostly outside the dense station clusters, which suggests gaps are more likely in less urban areas. However, this is a straight-line distance test using tract centroids, and the 2-mile buffer is a simple measure that does not reflect driving time, so actual EMS response times could be very different. It also depends on more factors such as vulnerable population density a block level.\n\n\n## Finally - A few comments about your incorporation of feedback!\nI improved the presentation of my portfolio by hiding setup code and unnecessary messages. I improved the presentation of my portfolio by hiding setup code and suppressing unnecessary messages. I removed my Census API key from the visible document and relied on environment variables instead.\n\n---\n\n\n\n",
    "supporting": [
      "lab2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}